// ===== CARDS DATABASE =====
export const CARDS = {
  base: [
    // === Hukum Konyol ===
    { id: 'b1', cat: 'Hukum Konyol', q: 'Di Florida, Amerika, wanita yang belum menikah dilarang melakukan [...] di hari Minggu.', a: 'Terjun Payung' },
    { id: 'b2', cat: 'Hukum Konyol', q: 'Di Swiss, ilegal untuk [...] di atas jam 10 malam di apartemen.', a: 'Menyiram Toilet' },
    { id: 'b3', cat: 'Hukum Konyol', q: 'Di Milan, Italia, secara hukum warga diwajibkan untuk [...] setiap saat kecuali di rumah sakit atau pemakaman.', a: 'Tersenyum' },
    { id: 'b4', cat: 'Hukum Konyol', q: 'Di Skotlandia, jika ada orang tak dikenal mengetuk pintumu dan meminta [...], kamu wajib membiarkannya masuk.', a: 'Menggunakan Toilet' },
    { id: 'b5', cat: 'Hukum Konyol', q: 'Di Samoa, adalah tindakan ilegal jika seorang suami lupa [...].', a: 'Ulang Tahun Istrinya' },
    { id: 'b6', cat: 'Hukum Konyol', q: 'Di Singapura, menjual atau membeli [...] adalah perbuatan ilegal sejak 1992.', a: 'Permen Karet' },
    { id: 'b7', cat: 'Hukum Konyol', q: 'Di Arkansas, Amerika, dilarang bagi seorang guru untuk menjelaskan [...] kepada murid-muridnya.', a: 'Teori Evolusi' },
    { id: 'b8', cat: 'Hukum Konyol', q: 'Di Perancis, secara hukum boleh menikahi seseorang yang sudah [...].', a: 'Meninggal Dunia' },
    { id: 'b9', cat: 'Hukum Konyol', q: 'Di Denmark, kamu wajib memeriksa [...] sebelum menyalakan mobilmu.', a: 'Kolong Mobil' },
    { id: 'b10', cat: 'Hukum Konyol', q: 'Di Kanada, 35% dari [...] di radio harus berasal dari artis Kanada.', a: 'Semua Musik yang Diputar' },
    { id: 'b11', cat: 'Hukum Konyol', q: 'Di Alabama, Amerika, dilarang mengenakan [...] di depan umum.', a: 'Fake Mustache yang Membuat Orang Tertawa di Gereja' },
    { id: 'b12', cat: 'Hukum Konyol', q: 'Di Oklahoma, dilarang memelihara [...] sebagai hewan peliharaan.', a: 'Trenggiling' },
    { id: 'b13', cat: 'Hukum Konyol', q: 'Di Inggris, kamu bisa ditangkap jika mati [...].', a: 'Di Gedung Parlemen' },
    { id: 'b14', cat: 'Hukum Konyol', q: 'Di Taiwan, kamu bisa didenda karena tidak [...] di restoran.', a: 'Menghabiskan Makananmu' },
    { id: 'b15', cat: 'Hukum Konyol', q: 'Di Thailand, dilarang meninggalkan rumah tanpa mengenakan [...].', a: 'Pakaian Dalam' },
    { id: 'b16', cat: 'Hukum Konyol', q: 'Di Portugal, dilarang [...] saat sedang berhadapan dengan seseorang.', a: 'Buang Air Kecil di Laut' },
    { id: 'b17', cat: 'Hukum Konyol', q: 'Di Venezuela, dilarang bermain [...] di tempat umum pada hari tertentu.', a: 'Catur' },
    { id: 'b18', cat: 'Hukum Konyol', q: 'Di Chicago, dilarang memberikan makan anjing dengan [...].', a: 'Wiski atau Bir' },
    { id: 'b19', cat: 'Hukum Konyol', q: 'Di Nepal, dilarang bagi seorang gadis untuk menikah dengan [...] menurut aturan tradisi tertentu.', a: 'Seseorang yang Lahir di Bulan yang Sama' },
    { id: 'b20', cat: 'Hukum Konyol', q: 'Di Australia, ilegal untuk mengubah [...] setelah jam 6 sore pada hari Sabtu.', a: 'Bola Lampu Listrik' },
    { id: 'b21', cat: 'Hukum Konyol', q: 'Di Yunani, dilarang mengenakan sepatu hak tinggi saat mengunjungi [...].', a: 'Situs Arkeologi' },
    { id: 'b22', cat: 'Hukum Konyol', q: 'Di Turkmenistan, presiden melarang siaran [...] di televisi negara.', a: 'Berita Cuaca' },
    { id: 'b23', cat: 'Hukum Konyol', q: 'Di Malaysia, dilarang menggunakan kata "[...]" dalam percakapan yang dianggap menghina kepala negara.', a: 'Kata "Gila" kepada Raja atau Keluarganya' },
    { id: 'b24', cat: 'Hukum Konyol', q: 'Di Norwegia, dilarang membunuh [...] yang terkenal karena pemandangan kota.', a: 'Ular Kobra' },
    { id: 'b25', cat: 'Hukum Konyol', q: 'Di Kansas, Amerika, dilarang makan [...] di piring ceri.', a: 'Ular' },
    { id: 'b26', cat: 'Hukum Konyol', q: 'Di Swedia, dilarang membeli [...] tapi diperbolehkan memilikinya.', a: 'Layanan Seksual' },
    { id: 'b27', cat: 'Hukum Konyol', q: 'Di Filipina, hukum melarang suami dan istri untuk [...] secara bersamaan.', a: 'Bercerai' },
    { id: 'b28', cat: 'Hukum Konyol', q: 'Di Rusia, hukum melarang penyebaran informasi bahwa [...] di antara anak-anak di bawah umur.', a: 'Hubungan LGBT "Normal"' },
    { id: 'b29', cat: 'Hukum Konyol', q: 'Di Irlandia, dilarang menjual [...] pada hari tertentu kecuali dibeli bersama makanan.', a: 'Alkohol di Hari Natal dan Jumat Agung' },
    { id: 'b30', cat: 'Hukum Konyol', q: 'Di Swiss, dilarang membuang air kencing sambil berdiri di [...] setelah jam 10 malam.', a: 'Apartemen' },

    // === Sejarah Aneh ===
    { id: 'b31', cat: 'Sejarah Aneh', q: 'Kaisar Romawi Caligula pernah mengangkat [...] menjadi senator.', a: 'Kuda Kesayangannya' },
    { id: 'b32', cat: 'Sejarah Aneh', q: 'Perang terpendek dalam sejarah adalah antara Inggris dan Zanzibar, berlangsung selama [...].', a: '38 Menit' },
    { id: 'b33', cat: 'Sejarah Aneh', q: 'Albert Einstein pernah ditawari posisi sebagai [...] tapi ia menolaknya.', a: 'Presiden Israel' },
    { id: 'b34', cat: 'Sejarah Aneh', q: 'Pada tahun 1919, Boston dilanda musibah besar ketika sebuah tangki meledak dan membanjiri kota dengan [...].', a: 'Sirup Molases' },
    { id: 'b35', cat: 'Sejarah Aneh', q: 'Napoleon Bonaparte pernah dikalahkan dalam pertempuran oleh [...].', a: 'Kelinci' },
    { id: 'b36', cat: 'Sejarah Aneh', q: 'Selama Perang Dunia II, Amerika memiliki rencana rahasia untuk menjatuhkan bom menggunakan [...].', a: 'Kelelawar' },
    { id: 'b37', cat: 'Sejarah Aneh', q: 'Cleopatra hidup lebih dekat ke era [...] daripada ke era pembangunan Piramida Giza.', a: 'iPhone' },
    { id: 'b38', cat: 'Sejarah Aneh', q: 'Ada sebuah perang yang dimulai karena perselisihan tentang [...] antara Honduras dan El Salvador.', a: 'Sepak Bola' },
    { id: 'b39', cat: 'Sejarah Aneh', q: 'Selama Olimpiade 1904, pelari maraton asal Kuba menyelesaikan lomba menggunakan [...] sebagai suplemen energi.', a: 'Strychnine' },
    { id: 'b40', cat: 'Sejarah Aneh', q: 'Kaisar Qin Shi Huang, pemersatu China, meninggal karena meminum [...] yang dipercaya memberi keabadian.', a: 'Pil Merkuri' },
    { id: 'b41', cat: 'Sejarah Aneh', q: 'Pada abad ke-17, Belanda mengalami krisis ekonomi disebut "Tulip Mania" di mana harga [...] bisa melebihi harga rumah.', a: 'Satu Umbi Bunga Tulip' },
    { id: 'b42', cat: 'Sejarah Aneh', q: 'Ada perang yang berlangsung 335 tahun antara Belanda dan [...] tanpa ada satu pun yang tewas.', a: 'Kepulauan Scilly' },
    { id: 'b43', cat: 'Sejarah Aneh', q: 'Presiden Amerika Abraham Lincoln adalah anggota dari [...] Hall of Fame — profesi di luar politik.', a: 'Wrestling Hall of Fame' },
    { id: 'b44', cat: 'Sejarah Aneh', q: 'Pada 1962, Amerika merencanakan untuk meledakkan [...] sebagai unjuk kekuatan terhadap Uni Soviet.', a: 'Bom Nuklir di Bulan' },
    { id: 'b45', cat: 'Sejarah Aneh', q: 'Di Inggris abad ke-18, ada profesi yang tugasnya tidur di kuburan untuk [...].', a: 'Menjaga Jenazah dari Pencuri Mayat' },
    { id: 'b46', cat: 'Sejarah Aneh', q: 'Pada Perang Dunia I, tentara Rusia sempat kehabisan amunisi dan membuat tentara mereka hanya memegang [...].', a: 'Sapu Lidi' },
    { id: 'b47', cat: 'Sejarah Aneh', q: 'Mesir Kuno pernah mencatat dalam sejarahnya protes buruh terorganisir pertama di dunia — para pekerja mogok karena tidak mendapat [...].', a: 'Jatah Bawang dan Bir' },
    { id: 'b48', cat: 'Sejarah Aneh', q: 'Tentara Mongol di bawah Jenghis Khan pernah menyerang sebuah kota dengan melontarkan [...] sebagai senjata biologi.', a: 'Mayat yang Terinfeksi Wabah' },
    { id: 'b49', cat: 'Sejarah Aneh', q: 'Pelukis terkenal Salvador Dalí tidak pernah membayar tagihan restoran — ia menulis [...] di balik cek yang ia beri ke kasir.', a: 'Gambar' },
    { id: 'b50', cat: 'Sejarah Aneh', q: 'Raja Henry VIII dari Inggris mengeluarkan hukum yang melarang rakyatnya untuk makan lebih dari [...] kali sehari.', a: 'Dua Kali Sehari' },

    // === Dunia Hewan ===
    { id: 'b51', cat: 'Dunia Hewan', q: 'Susu dari kuda nil ternyata berwarna [...].', a: 'Merah Muda' },
    { id: 'b52', cat: 'Dunia Hewan', q: 'Jantung dari seekor udang terletak di [...].', a: 'Kepalanya' },
    { id: 'b53', cat: 'Dunia Hewan', q: 'Bintang laut adalah hewan yang tidak memiliki [...].', a: 'Otak' },
    { id: 'b54', cat: 'Dunia Hewan', q: 'Gurita memiliki [...] jantung yang berbeda.', a: 'Tiga' },
    { id: 'b55', cat: 'Dunia Hewan', q: 'Seekor siput dapat tidur selama [...] tanpa gangguan.', a: '3 Tahun' },
    { id: 'b56', cat: 'Dunia Hewan', q: 'Gajah adalah satu-satunya hewan yang tidak bisa [...].', a: 'Melompat' },
    { id: 'b57', cat: 'Dunia Hewan', q: 'Kupu-kupu merasakan rasa makanan menggunakan [...].', a: 'Kakinya' },
    { id: 'b58', cat: 'Dunia Hewan', q: 'Sekelompok flamingo disebut [...] dalam bahasa Inggris.', a: 'Flamboyance' },
    { id: 'b59', cat: 'Dunia Hewan', q: 'Lumba-lumba tidur dengan [...] yang tetap terjaga.', a: 'Setengah Otak' },
    { id: 'b60', cat: 'Dunia Hewan', q: 'Spesies ubur-ubur Turritopsis dohrnii dikenal sebagai satu-satunya makhluk yang bisa [...].', a: 'Hidup Abadi' },
    { id: 'b61', cat: 'Dunia Hewan', q: 'Cumi-cumi raksasa memiliki mata terbesar di antara semua makhluk hidup — berdiameter hingga [...].', a: '30 cm' },
    { id: 'b62', cat: 'Dunia Hewan', q: 'Kuda laut adalah satu-satunya makhluk di mana sang [...] yang mengandung dan melahirkan anaknya.', a: 'Jantan' },
    { id: 'b63', cat: 'Dunia Hewan', q: 'Berang-berang sungai saat tidur mengapung di air dan berpegangan tangan satu sama lain agar tidak [...].', a: 'Hanyut Terpisah' },
    { id: 'b64', cat: 'Dunia Hewan', q: 'Burung kenari jantan bisa mempelajari lagu baru setiap tahun karena setiap musim dingin [...].', a: 'Sebagian Otaknya Mati dan Tumbuh Lagi di Musim Semi' },
    { id: 'b65', cat: 'Dunia Hewan', q: 'Hiu adalah hewan tertua dari semua makhluk bertulang di bumi — mereka ada sebelum [...].', a: 'Pohon Pertama Muncul di Bumi' },
    { id: 'b66', cat: 'Dunia Hewan', q: 'Tikus bisa merasakan [...] dan menyesal atas keputusan yang salah, menurut penelitian ilmiah.', a: 'Penyesalan' },
    { id: 'b67', cat: 'Dunia Hewan', q: 'Jerapah hanya tidur sekitar [...] jam per hari dalam kondisi liar.', a: '30 Menit' },
    { id: 'b68', cat: 'Dunia Hewan', q: 'Wombat adalah satu-satunya hewan yang kotorannya berbentuk [...].', a: 'Kubus' },
    { id: 'b69', cat: 'Dunia Hewan', q: 'Harimau putih yang sering kita lihat di kebun binatang hampir semua merupakan hasil dari proses [...].', a: 'Inbreeding' },
    { id: 'b70', cat: 'Dunia Hewan', q: 'Salmon yang sudah kembali ke sungai untuk bertelur akan [...] setelah proses pemijahan selesai.', a: 'Mati' },

    // === Penemuan ===
    { id: 'b71', cat: 'Penemuan', q: 'Benda yang pertama kali memiliki barcode untuk di-scan di supermarket adalah [...].', a: "Permen Karet Wrigley's" },
    { id: 'b72', cat: 'Penemuan', q: 'Penemu dari mesin pembuat permen kapas ternyata berprofesi sebagai [...].', a: 'Dokter Gigi' },
    { id: 'b73', cat: 'Penemuan', q: 'Chainsaw (gergaji mesin) awalnya diciptakan pada abad ke-18 untuk membantu proses [...].', a: 'Persalinan' },
    { id: 'b74', cat: 'Penemuan', q: 'High heels (sepatu hak tinggi) pertama kali diciptakan di Persia untuk dipakai oleh [...].', a: 'Tentara Berkuda Pria' },
    { id: 'b75', cat: 'Penemuan', q: 'Bubble wrap pada awalnya diciptakan untuk dijadikan sebagai [...].', a: 'Wallpaper Dinding' },
    { id: 'b76', cat: 'Penemuan', q: 'Nintendo, perusahaan game terkenal, awalnya memproduksi [...] sebelum beralih ke teknologi.', a: 'Kartu Main' },
    { id: 'b77', cat: 'Penemuan', q: 'Post-it Note (kertas tempel kuning) diciptakan karena sang penemu awalnya mencoba membuat [...] yang gagal.', a: 'Lem Super Kuat' },
    { id: 'b78', cat: 'Penemuan', q: 'Microwave oven ditemukan secara tidak sengaja ketika seorang insinyur sedang mengerjakan [...].', a: 'Radar Militer' },
    { id: 'b79', cat: 'Penemuan', q: 'Permainan Monopoli awalnya diciptakan untuk mendemonstrasikan bahaya dari [...].', a: 'Sistem Ekonomi Kapitalis' },
    { id: 'b80', cat: 'Penemuan', q: 'Tas belanja plastik awalnya dipromosikan sebagai pilihan yang [...] dibanding tas kertas.', a: 'Lebih Ramah Lingkungan' },
    { id: 'b81', cat: 'Penemuan', q: 'Velcro (perekat rambut) diciptakan setelah seorang insinyur Swiss mengamati [...] yang menempel di baju dan rambut anjingnya.', a: 'Biji Tanaman Burdock' },
    { id: 'b82', cat: 'Penemuan', q: 'Coca-Cola ditemukan oleh seorang apoteker yang mencoba membuat obat untuk [...].', a: 'Kecanduan Morfin dan Sakit Kepala' },
    { id: 'b83', cat: 'Penemuan', q: 'WD-40, cairan pelumas populer, mendapat namanya karena percobaan formula ke-[...] berhasil.', a: '40' },
    { id: 'b84', cat: 'Penemuan', q: 'Play-Doh awalnya diciptakan bukan sebagai mainan, melainkan sebagai [...].', a: 'Pembersih Wallpaper' },
    { id: 'b85', cat: 'Penemuan', q: 'Superglue (lem super) ditemukan secara tidak sengaja saat ilmuwan mencoba menciptakan [...] pada masa Perang Dunia II.', a: 'Lensa Senapan yang Jernih' },
    { id: 'b86', cat: 'Penemuan', q: 'Slinky (mainan per spiral) ditemukan ketika seorang insinyur laut menjatuhkan [...] dari mejanya.', a: 'Per Tension' },
    { id: 'b87', cat: 'Penemuan', q: 'Saccharin (pemanis buatan pertama) ditemukan secara tidak sengaja oleh seorang ahli kimia yang [...] setelah bekerja di lab.', a: 'Lupa Mencuci Tangannya Sebelum Makan dan Merasakan Manisnya' },
    { id: 'b88', cat: 'Penemuan', q: 'Penicillin (antibiotik pertama) ditemukan oleh Alexander Fleming yang melihat [...] pada cawan petri-nya yang terkontaminasi.', a: 'Jamur yang Membunuh Bakteri di Sekitarnya' },
    { id: 'b89', cat: 'Penemuan', q: 'Pacemaker jantung pertama ditemukan secara kebetulan ketika seorang ilmuwan salah memilih [...] ukuran saat merakit alat.', a: 'Resistor yang Terlalu Kecil' },
    { id: 'b90', cat: 'Penemuan', q: 'Minuman energi Red Bull didasarkan pada minuman Thailand bernama [...] yang awalnya dibuat untuk pekerja kasar.', a: 'Krating Daeng' },

    // === Fakta Absurd ===
    { id: 'b91', cat: 'Fakta Absurd', q: 'Keringat ketakutan manusia memiliki bau yang mirip dengan [...].', a: 'Bawang Merah' },
    { id: 'b92', cat: 'Fakta Absurd', q: 'Astronot di luar angkasa tidak bisa [...] karena tidak ada gravitasi yang memisahkan cairan dari gas di lambung.', a: 'Sendawa' },
    { id: 'b93', cat: 'Fakta Absurd', q: 'Buah pisang secara botani diklasifikasikan bukan sebagai buah biasa melainkan sebagai [...].', a: 'Berry' },
    { id: 'b94', cat: 'Fakta Absurd', q: 'Oxford University lebih tua dari [...].', a: 'Kekaisaran Aztec' },
    { id: 'b95', cat: 'Fakta Absurd', q: 'Rata-rata orang menelan sekitar [...] laba-laba saat tidur dalam seumur hidup.', a: 'Nol' },
    { id: 'b96', cat: 'Fakta Absurd', q: 'Rasa pedas bukan rasa yang dideteksi oleh indera perasa, melainkan [...].', a: 'Respons Saraf Nyeri' },
    { id: 'b97', cat: 'Fakta Absurd', q: 'Bersin dengan mata terbuka adalah [...] secara fisik.', a: 'Tidak Mungkin' },
    { id: 'b98', cat: 'Fakta Absurd', q: 'Madu adalah satu-satunya makanan yang [...] dan tidak pernah basi.', a: 'Bisa Bertahan Ribuan Tahun Tanpa Rusak' },
    { id: 'b99', cat: 'Fakta Absurd', q: 'Tiap tahun, ada lebih banyak orang yang meninggal akibat [...] daripada akibat serangan hiu.', a: 'Selfie' },
    { id: 'b100', cat: 'Fakta Absurd', q: 'Warna yang paling pertama dirasakan oleh bayi manusia yang baru lahir adalah [...].', a: 'Merah' },
    { id: 'b101', cat: 'Fakta Absurd', q: 'Jika kamu menggali lubang tembus dari satu sisi Bumi ke sisi lainnya dan melompat, kamu akan sampai di sisi lain dalam waktu sekitar [...].', a: '42 Menit' },
    { id: 'b102', cat: 'Fakta Absurd', q: 'Sidik jari koala sangat mirip dengan manusia sehingga pernah [...] pada TKP kejahatan.', a: 'Membuat Bingung Para Penyidik Forensik' },
    { id: 'b103', cat: 'Fakta Absurd', q: 'Setiap menit, rata-rata tubuh manusia menghasilkan sekitar [...] sel darah merah baru.', a: '2 Juta Sel Darah Merah' },
    { id: 'b104', cat: 'Fakta Absurd', q: 'Suara yang kamu dengar saat mendekatkan telinga ke kerang bukan suara laut, melainkan [...].', a: 'Suara Darah yang Mengalir di Telingamu Sendiri' },
    { id: 'b105', cat: 'Fakta Absurd', q: 'Manusia adalah satu-satunya hewan yang bisa [...] dan menyadari mereka sedang melakukannya pada saat yang sama.', a: 'Tertawa Sendiri' },
    { id: 'b106', cat: 'Fakta Absurd', q: 'Kuku manusia tumbuh sekitar [...] mm per bulan, dan kuku jari tangan tumbuh lebih cepat dari kuku jari kaki.', a: '3-4 mm Per Bulan' },
    { id: 'b107', cat: 'Fakta Absurd', q: 'Kentut manusia cukup flammable (mudah terbakar) karena mengandung gas [...].', a: 'Metana dan Hidrogen' },
    { id: 'b108', cat: 'Fakta Absurd', q: 'Manusia kehilangan sekitar [...] rambut per hari secara normal.', a: '50-100 Helai Rambut' },
    { id: 'b109', cat: 'Fakta Absurd', q: 'Kita tidak pernah bisa menggelitik diri sendiri karena otak [...] sebelum jari menyentuh kulit.', a: 'Memprediksi Sentuhan dan Menghilangkan Efek Kejutannya' },
    { id: 'b110', cat: 'Fakta Absurd', q: 'Dinding Berlin yang memisahkan Jerman Barat dan Timur berdiri selama [...] tahun.', a: '28 Tahun' },
  ],

  popkultur: [
    { id: 'p1', cat: 'Pop Kultur', q: 'Film "The Dark Knight" (2008) nyaris batal produksi karena studio Warner Bros. ingin mengganti sutradara Christopher Nolan dengan [...].', a: 'Brett Ratner' },
    { id: 'p2', cat: 'Pop Kultur', q: 'Lady Gaga aslinya diterima kuliah di [...] tapi keluar setelah setahun untuk mengejar karir musik.', a: 'NYU Tisch School of the Arts' },
    { id: 'p3', cat: 'Pop Kultur', q: 'Aktor yang memerankan Jack di Titanic (1997) hampir bukan Leonardo DiCaprio. Peran itu hampir diberikan kepada [...].', a: 'River Phoenix' },
    { id: 'p4', cat: 'Pop Kultur', q: 'Band The Beatles pernah ditolak oleh perusahaan rekaman Decca Records dengan alasan [...].', a: '"Grup gitar sudah tidak laku lagi"' },
    { id: 'p5', cat: 'Pop Kultur', q: 'Lagu "Bohemian Rhapsody" oleh Queen dirilis tanpa izin dari label karena eksekutif label menolak lagu itu sebab [...].', a: 'Terlalu Panjang untuk Diputar di Radio' },
    { id: 'p6', cat: 'Pop Kultur', q: 'Spongebob Squarepants awalnya bernama [...] dalam rancangan awal sang kreator Stephen Hillenburg.', a: 'SpongeBoy' },
    { id: 'p7', cat: 'Pop Kultur', q: 'Film Harry Potter and the Sorcerer\'s Stone sempat ditolak oleh [...] penerbit sebelum akhirnya diterbitkan oleh Bloomsbury.', a: '12 Penerbit' },
    { id: 'p8', cat: 'Pop Kultur', q: 'Seluruh franchise film Marvel Cinematic Universe (MCU) hampir tidak ada karena Marvel Studios hampir bangkrut dan hampir menjual hak karakter Iron Man kepada [...].', a: 'New Line Cinema' },
    { id: 'p9', cat: 'Pop Kultur', q: 'Michael Jackson pernah mengajukan diri untuk membeli hak karakter [...] kepada Marvel, tapi ditolak.', a: 'Spider-Man' },
    { id: 'p10', cat: 'Pop Kultur', q: 'Film Avatar (2009) sempat ditunda produksinya selama lebih dari 10 tahun oleh James Cameron karena [...].', a: 'Teknologi CGI Belum Siap' },
    { id: 'p11', cat: 'Pop Kultur', q: 'Karakter Walter White di Breaking Bad awalnya direncanakan akan dimainkan oleh [...] bukan Bryan Cranston.', a: 'Matthew Broderick' },
    { id: 'p12', cat: 'Pop Kultur', q: 'Nama "007" untuk karakter James Bond terinspirasi dari [...].', a: 'Nomor Bus yang Dinaiki Ian Fleming' },
    { id: 'p13', cat: 'Pop Kultur', q: 'Film Shrek awalnya dirancang untuk dibintangi oleh [...] sebagai pengisi suara Shrek.', a: 'Chris Farley' },
    { id: 'p14', cat: 'Pop Kultur', q: 'Lagu "Happy Birthday to You" pernah memiliki hak cipta yang dipegang oleh [...] hingga tahun 2016.', a: 'Warner' },
    { id: 'p15', cat: 'Pop Kultur', q: 'Franchise film "Home Alone" awalnya dibuat karena sutradara Chris Columbus ingin membuat film tentang [...] yang terjebak di rumah.', a: 'Pencuri yang Terperangkap' },
    { id: 'p16', cat: 'Pop Kultur', q: 'Tokoh Joker di film "The Dark Knight" dimainkan oleh Heath Ledger yang kabarnya [...] demi mempersiapkan peran tersebut.', a: 'Mengurung Diri di Kamar Hotel Selama Sebulan' },
    { id: 'p17', cat: 'Pop Kultur', q: 'Serial anime Naruto berlangsung selama [...] episode, termasuk semua fillernya.', a: '720 Episode' },
    { id: 'p18', cat: 'Pop Kultur', q: 'Karakter Elsa di film Frozen awalnya dirancang sebagai antagonis utama, bukan [...].', a: 'Protagonis' },
    { id: 'p19', cat: 'Pop Kultur', q: 'Film "Parasite" (2019) dari Korea adalah film berbahasa non-Inggris pertama yang memenangkan [...] di Academy Awards.', a: 'Best Picture' },
    { id: 'p20', cat: 'Pop Kultur', q: 'Soundtrack film Interstellar yang ikonik diciptakan oleh Hans Zimmer yang sengaja tidak menonton trailernya agar [...].', a: 'Tidak Terpengaruh Visual Saat Membuat Musik' },
    { id: 'p21', cat: 'Pop Kultur', q: 'Game "Among Us" yang viral di tahun 2020 sebenarnya dirilis pada tahun [...] tapi hampir tidak ada yang memainkannya.', a: '2018' },
    { id: 'p22', cat: 'Pop Kultur', q: 'Karakter "Eleven" di Stranger Things awalnya ditulis sebagai tokoh laki-laki bernama [...].', a: '"Mathew" atau "Mike"' },
    { id: 'p23', cat: 'Pop Kultur', q: 'Film "Titanic" (1997) memiliki budget yang lebih besar dari kapal Titanic sesungguhnya yang [...] dibangun.', a: 'Biaya Pembuatan Kapal Aslinya' },
    { id: 'p24', cat: 'Pop Kultur', q: 'Penulis novel "Harry Potter" J.K. Rowling pernah sangat miskin sampai [...] sebelum bukunya sukses besar.', a: 'Hidup dari Tunjangan Sosial' },
    { id: 'p25', cat: 'Pop Kultur', q: 'Taylor Swift menulis lagu "You Belong With Me" dalam waktu [...] menit.', a: '15-20 Menit' },
    { id: 'p26', cat: 'Pop Kultur', q: 'Seri buku "A Song of Ice and Fire" (Game of Thrones) belum selesai ditulis oleh George R.R. Martin — buku terakhirnya sudah ditunggu sejak [...].', a: '2011' },
    { id: 'p27', cat: 'Pop Kultur', q: 'Keanu Reeves menyumbangkan hampir seluruh honornya dari film Matrix kepada tim [...] karena menghargai kerja keras mereka.', a: 'Spesialis Efek Visual' },
    { id: 'p28', cat: 'Pop Kultur', q: 'Lagu "Baby Shark" yang viral adalah lagu dengan penonton terbanyak di YouTube — melampaui [...] miliar penonton.', a: '13+ Miliar Views' },
    { id: 'p29', cat: 'Pop Kultur', q: 'Film "The Lion King" (1994) sebenarnya adalah adaptasi tidak resmi dari drama Shakespeare berjudul [...].', a: 'Hamlet' },
    { id: 'p30', cat: 'Pop Kultur', q: 'Kata "selfie" pertama kali digunakan secara online pada tahun [...] oleh seorang pria Australia yang memfoto luka bibirnya.', a: '2002' },
    { id: 'p31', cat: 'Pop Kultur', q: 'Emoji pertama kali diciptakan di Jepang pada tahun [...] bukan oleh Apple atau Google.', a: '1999' },
    { id: 'p32', cat: 'Pop Kultur', q: 'Di balik suara robot WALL-E dalam film Pixar, sebenarnya diisi oleh [...].', a: 'Ben Burtt' },
    { id: 'p33', cat: 'Pop Kultur', q: 'Serial "The Office" versi Amerika nyaris dibatalkan setelah episode pilot karena rating yang sangat buruk — diselamatkan karena [...].', a: 'Eksekutif NBC Percaya pada Potensi Jangka Panjangnya' },
    { id: 'p34', cat: 'Pop Kultur', q: 'Kartu Pokemon pertama yang paling mahal terjual seharga [...] juta dolar di lelang.', a: 'Lebih dari 5 Juta Dolar' },
    { id: 'p35', cat: 'Pop Kultur', q: 'Tokoh "Deadpool" awalnya sangat dibenci versi filmnya yang pertama (X-Men Origins) karena [...].', a: 'Mulutnya Dijahit dan Semua Kekuatannya Diubah Total' },
    { id: 'p36', cat: 'Pop Kultur', q: 'Lagu tema Titanic "My Heart Will Go On" hampir tidak ada di film karena James Cameron [...].', a: 'Tidak Suka Lagu Itu dan Hampir Memotongnya' },
    { id: 'p37', cat: 'Pop Kultur', q: 'Film "Toy Story" (1995) hampir gagal produksi di tengah jalan karena karakter Woody aslinya sangat [...].', a: 'Jahat, Kasar, dan Tidak Disukai Tim Produksi' },
    { id: 'p38', cat: 'Pop Kultur', q: 'Brand Supreme yang eksklusif awalnya hanyalah sebuah toko kecil di New York yang menjual [...].', a: 'Pakaian dan Perlengkapan Skateboard' },
    { id: 'p39', cat: 'Pop Kultur', q: 'Film "The Wizard of Oz" (1939) menggunakan [...] sebagai bahan untuk embuat baju karakter Witch yang berwarna hijau.', a: 'Tembaga' },
    { id: 'p40', cat: 'Pop Kultur', q: 'Dalam film James Bond, karakter "M" perempuan pertama diperankan oleh Judi Dench — sebelumnya M selalu [...].', a: 'Pria' },
    { id: 'p41', cat: 'Pop Kultur', q: 'Nama penyangun Ed Sheeran terinspirasi dari nama artis [...] yang ia idolakan saat kecil.', a: 'Eminem' },
    { id: 'p42', cat: 'Pop Kultur', q: 'Film "Mad Max: Fury Road" butuh [...] hari syuting di lapangan terbuka di gurun Namibia.', a: 'Lebih dari 120 Hari' },
    { id: 'p43', cat: 'Pop Kultur', q: 'Pemain Harry Potter Daniel Radcliffe pernah mengungkapkan ia kecanduan [...] selama masa syuting serial Potter.', a: 'Alkohol' },
    { id: 'p44', cat: 'Pop Kultur', q: 'Kata "Google" berasal dari kata matematika "[...]" yang berarti angka 1 diikuti 100 nol.', a: 'Googol' },
    { id: 'p45', cat: 'Pop Kultur', q: 'Film "Schindler\'s List" (1993) adalah pertama kalinya Steven Spielberg menangis saat [...].', a: 'Menonton Hasil Akhir Filmnya Sendiri' },
    { id: 'p46', cat: 'Pop Kultur', q: 'Kartu yugioh asli milik Seto Kaiba "Blue Eyes White Dragon" dalam dunia nyata pernah terjual seharga [...].', a: 'Ratusan Ribu Dolar di Lelang Kartu Resmi' },
    { id: 'p47', cat: 'Pop Kultur', q: 'Serial anime One Piece sudah berlangsung lebih dari 25 tahun dan memiliki lebih dari [...] chapter manga.', a: '1100+ Chapter' },
    { id: 'p48', cat: 'Pop Kultur', q: 'Aktor Jim Carrey dibayar hanya [...] dolar untuk film Ace Ventura pertamanya, tapi menetapkan bayaran 20 juta untuk Dumb and Dumber.', a: '350 Ribu Dolar' },
    { id: 'p49', cat: 'Pop Kultur', q: 'Lagu "Smells Like Teen Spirit" oleh Nirvana direkam dalam satu malam dan Kurt Cobain mengakui liriknya terinspirasi dari [...].', a: 'Coretan di Tembok Kamar Temannya' },
    { id: 'p50', cat: 'Pop Kultur', q: 'Film "Inception" oleh Christopher Nolan dikerjakan selama [...] tahun sejak konsep awal hingga rilis.', a: '10 Tahun' },
  ],

  olahraga: [
    { id: 'o1', cat: 'Olahraga', q: 'Pada Olimpiade 1900 di Paris, salah satu cabang olahraga yang dipertandingkan adalah [...], yang tidak pernah diulang lagi.', a: 'Panjat Tiang' },
    { id: 'o2', cat: 'Olahraga', q: 'Usain Bolt, sprinter tercepat di dunia, mengonsumsi [...] setiap hari selama Olimpiade Beijing 2008.', a: "1.000 Chicken McNuggets McDonald's" },
    { id: 'o3', cat: 'Olahraga', q: 'Dalam Piala Dunia 1930, final antara Uruguay dan Argentina sempat tertunda karena kedua tim berdebat tentang [...].', a: 'Mana Bola yang Digunakan' },
    { id: 'o4', cat: 'Olahraga', q: 'Olahraga golf dimainkan di Bulan oleh astronot Alan Shepard dengan menggunakan [...].', a: 'Stik Golf yang Dibawa Diam-diam dari Bumi' },
    { id: 'o5', cat: 'Olahraga', q: 'Pada tahun 1994, kiper tim nasional Kolombia Andrés Escobar ditembak mati karena [...].', a: 'Mencetak Gol Bunuh Diri di Piala Dunia' },
    { id: 'o6', cat: 'Olahraga', q: 'Lance Armstrong, juara Tour de France 7 kali, akhirnya dicopot semua gelarnya karena [...].', a: 'Doping' },
    { id: 'o7', cat: 'Olahraga', q: 'Olahraga Quidditch (dari Harry Potter) kini sudah dimainkan secara nyata dan memiliki liga internasional, termasuk di [...].', a: 'Indonesia' },
    { id: 'o8', cat: 'Olahraga', q: 'Aturan offside dalam sepak bola lahir karena tim Sheffield FC ingin mencegah taktik [...].', a: 'Pemain Menunggu di Dekat Gawang Lawan' },
    { id: 'o9', cat: 'Olahraga', q: 'Michael Jordan pernah diskors dari NBA karena diduga secara diam-diam bermain [...] profesional.', a: 'Poker' },
    { id: 'o10', cat: 'Olahraga', q: 'Kiper legendaris Rusia Lev Yashin mendapat julukan "Black Spider" karena konon ia telah menyelamatkan [...] penalti sepanjang karir.', a: '150 Tendangan Penalti' },
    { id: 'o11', cat: 'Olahraga', q: 'Seorang pesepakbola amatir bernama John Landy berlari maraton sambil berhenti untuk [...] seorang lawan yang terjatuh, dan tetap menyelesaikan lomba.', a: 'Membantu' },
    { id: 'o12', cat: 'Olahraga', q: 'Dalam pertandingan resmi cricket, sebuah pertandingan antara Inggris dan Zimbabwe berlangsung selama [...].', a: '9 Hari Penuh' },
    { id: 'o13', cat: 'Olahraga', q: 'Pelari maraton Dorando Pietri di Olimpiade London 1908 hampir memenangkan medali emas tapi didiskualifikasi karena [...].', a: 'Dibantu Oleh Panitia Saat Hampir Pingsan di Garis Finish' },
    { id: 'o14', cat: 'Olahraga', q: 'Bola basket NBA memiliki [...] lekukan (pebble) di permukaannya.', a: '122 Lekukan' },
    { id: 'o15', cat: 'Olahraga', q: 'Bola sepak yang digunakan di Piala Dunia 2010 di Afrika Selatan bernama "Jabulani" sangat dikritik para kiper karena [...].', a: 'Lintasannya Tidak Bisa Diprediksi' },
    { id: 'o16', cat: 'Olahraga', q: 'Petinju Muhammad Ali kehilangan gelar dunianya bukan karena kalah di ring, melainkan karena [...].', a: 'Menolak Wajib Militer ke Vietnam' },
    { id: 'o17', cat: 'Olahraga', q: 'Serena Williams memenangkan Australian Open 2017 saat ia sedang hamil [...] minggu.', a: '8 Minggu' },
    { id: 'o18', cat: 'Olahraga', q: 'Di Olimpiade 1904, maraton dimenangi oleh pelari Amerika Fred Lorz yang sebenarnya [...] sebagian besar rutenya.', a: 'Naik Mobil' },
    { id: 'o19', cat: 'Olahraga', q: 'Lionel Messi saat kecil menderita kekurangan hormon pertumbuhan dan biaya pengobatannya awalnya ditanggung oleh [...].', a: 'FC Barcelona' },
    { id: 'o20', cat: 'Olahraga', q: 'Tiger Woods pertama kali bermain golf di TV saat usianya baru [...] tahun.', a: '2 Tahun' },
    { id: 'o21', cat: 'Olahraga', q: 'Aturan bahwa pemain sepak bola harus mengenakan sepatu saat pertandingan baru resmi diberlakukan pada tahun [...].', a: '1890-an' },
    { id: 'o22', cat: 'Olahraga', q: 'Seorang atlet Olimpiade Ethiopia bernama Abebe Bikila memenangkan maraton Olimpiade 1960 dengan berlari [...].', a: 'Tanpa Alas Kaki' },
    { id: 'o23', cat: 'Olahraga', q: 'Dalam sejarah NBA, Tim Chicago Bulls meraih rekor menang terbanyak dalam satu musim dengan [...] kemenangan.', a: '72 Kemenangan dari 82 Pertandingan' },
    { id: 'o24', cat: 'Olahraga', q: 'Pemain tenis yang pernah memenangkan semua 4 Grand Slam dalam satu tahun kalender — "Golden Slam" — pertama kali dilakukan oleh [...].', a: 'Steffi Graf' },
    { id: 'o25', cat: 'Olahraga', q: 'Sebuah pertandingan bola basket NBA pernah dimenangkan dengan selisih [...] poin dalam sejarah.', a: '68 Poin' },
    { id: 'o26', cat: 'Olahraga', q: 'Kriket versi T20 (Twenty20) pertama kali diperkenalkan pada tahun [...] sebagai cara membuat kriket lebih menarik bagi penonton.', a: '2003' },
    { id: 'o27', cat: 'Olahraga', q: 'Perenang legendaris Michael Phelps memiliki rentang tangan (wingspan) sepanjang [...] yang membuatnya memiliki keunggulan biologis.', a: '201 cm' },
    { id: 'o28', cat: 'Olahraga', q: 'Cristiano Ronaldo menyumbangkan uang bonus Ballon d\'Or-nya untuk [...] saat memenangkan penghargaan tersebut.', a: 'Membangun Sekolah dan Memberikan Donasi ke Panti Asuhan' },
    { id: 'o29', cat: 'Olahraga', q: 'Olahraga Sumo tidak pernah memiliki batasan berat badan minimum — petarung terkecil yang pernah bertanding di level tertinggi beratnya hanya [...] kg.', a: '100 kg' },
    { id: 'o30', cat: 'Olahraga', q: 'Permainan Rugby mendapat namanya dari kota [...] di Inggris tempat pertama kali dimainkan secara formal.', a: 'Rugby, Warwickshire, Inggris' },
    { id: 'o31', cat: 'Olahraga', q: 'Perenang Amerika Janet Evans adalah satu-satunya orang yang memenangkan medali emas Olimpiade di antara dua Olimpiade yang jaraknya [...] tahun.', a: '12 Tahun' },
    { id: 'o32', cat: 'Olahraga', q: 'Balap Formula 1 pertama kali diadakan secara resmi pada tahun [...] di Sirkuit Silverstone, Inggris.', a: '1950' },
    { id: 'o33', cat: 'Olahraga', q: 'Rekor lompat jauh Olimpiade milik Bob Beamon yang dicetak pada tahun 1968 bertahan selama [...] tahun sebelum dipecahkan.', a: '23 Tahun' },
    { id: 'o34', cat: 'Olahraga', q: 'Manchester United dan Manchester City bermain di stadion yang hanya berjarak sekitar [...] km satu sama lain.', a: 'Sekitar 5 km' },
    { id: 'o35', cat: 'Olahraga', q: 'Atlet bulu tangkis Indonesia Kevin Sanjaya Sukamuljo pernah mendapat julukan "[...]" dari komunitas bulu tangkis dunia.', a: '"The Minion"' },
    { id: 'o36', cat: 'Olahraga', q: 'Olimpiade pertama era modern diadakan di Athena, Yunani pada tahun [...].', a: '1896' },
    { id: 'o37', cat: 'Olahraga', q: 'Legenda sepak bola Brasil Ronaldo "El Fenomeno" pernah mengalami kejang misterius sebelum Final Piala Dunia 1998 tapi tetap [...].', a: 'Bermain dan Masuk Skuad Final' },
    { id: 'o38', cat: 'Olahraga', q: 'Pelari Kenya Eliud Kipchoge adalah manusia pertama yang menyelesaikan maraton di bawah [...] jam.', a: '2 Jam' },
    { id: 'o39', cat: 'Olahraga', q: 'Dalam sepak bola, wasit pertama kali menggunakan peluit di pertandingan resmi pada tahun [...].', a: '1878' },
    { id: 'o40', cat: 'Olahraga', q: 'Liga Primer Inggris (Premier League) didirikan pada tahun [...] setelah memisahkan diri dari Football League.', a: '1992' },
    { id: 'o41', cat: 'Olahraga', q: 'Bola yang digunakan di pertandingan tenis Wimbledon harus disimpan pada suhu [...] derajat Celsius sebelum digunakan.', a: '20 Derajat Celsius' },
    { id: 'o42', cat: 'Olahraga', q: 'Pesepakbola Zlatan Ibrahimovic mencetak gol dengan tendangan salto dari jarak [...] meter saat melawan Inggris — disebut salah satu gol terbaik sepanjang masa.', a: '30 Meter' },
    { id: 'o43', cat: 'Olahraga', q: 'Olahraga Esports (game kompetitif) sudah diakui sebagai cabang olahraga resmi di [...] negara.', a: 'Lebih dari 50 Negara' },
    { id: 'o44', cat: 'Olahraga', q: 'Di Olimpiade musim dingin, salah satu cabang olahraga paling aneh adalah "[...]" di mana atlet membersihkan lintasan es di depan batu besar.', a: 'Curling' },
    { id: 'o45', cat: 'Olahraga', q: 'Seorang pemanah Turki bernama Yusuf Dikec memenangkan medali perak Olimpiade Paris 2024 dengan cara yang viral karena [...].', a: 'Tangan Satunya Dimasukkan ke Saku' },
    { id: 'o46', cat: 'Olahraga', q: 'Dalam sejarah UFC, petinju Conor McGregor pernah KO lawan hanya dalam waktu [...] detik.', a: '13 Detik' },
    { id: 'o47', cat: 'Olahraga', q: 'Olahraga sepak bola di Amerika Serikat menyebut "football" untuk olahraga yang menggunakan [...], bukan kaki.', a: 'Bola Oval dan Tangan' },
    { id: 'o48', cat: 'Olahraga', q: 'Pemain basket LeBron James memenangkan NBA Championship bersama [...] tim yang berbeda sepanjang karirnya.', a: '3 Tim' },
    { id: 'o49', cat: 'Olahraga', q: 'Dalam sejarah Grand Slam tenis, Roger Federer pertama kali memenangkan Wimbledon pada usia [...] tahun.', a: '21 Tahun' },
    { id: 'o50', cat: 'Olahraga', q: 'Piala Dunia 2022 di Qatar adalah pertama kalinya Piala Dunia diadakan di [...].', a: 'Bulan November-Desember' },
    { id: 'o51', cat: 'Olahraga', q: 'Bola basket pertama kali menggunakan ring dan jaring seperti sekarang — sebelumnya menggunakan [...].', a: 'Keranjang Buah Persik' },
    { id: 'o52', cat: 'Olahraga', q: 'Gol yang disebut "Gol Tangan Tuhan" dicetak oleh Diego Maradona dengan [...] pada Piala Dunia 1986.', a: 'Tangannya' },
  ],

  makanan: [
    { id: 'm1', cat: 'Kuliner', q: 'Pringles secara hukum di Inggris sempat dinyatakan bukan sebagai kentang oleh pengadilan pajak, melainkan sebagai [...].', a: 'Kue' },
    { id: 'm2', cat: 'Kuliner', q: 'Bahan pewarna makanan merah alami "carmine" yang digunakan di berbagai produk didapat dari [...].', a: 'Kutu Kermes' },
    { id: 'm3', cat: 'Kuliner', q: 'Kopi Luwak yang mahal itu dibuat dari biji kopi yang sebelumnya telah [...] oleh hewan musang luwak.', a: 'Dimakan dan Dikeluarkan Lewat Kotoran' },
    { id: 'm4', cat: 'Kuliner', q: 'Ketchup (saus tomat) pada abad ke-19 awalnya dijual sebagai [...].', a: 'Obat-obatan' },
    { id: 'm5', cat: 'Kuliner', q: 'Cokelat panas (hot chocolate) yang dikonsumsi oleh bangsa Maya kuno disajikan [...].', a: 'Dingin dan Berbusa' },
    { id: 'm6', cat: 'Kuliner', q: 'Vanila asli (bukan sintetis) didapatkan dari [...].', a: 'Buah Anggrek Vanilla planifolia' },
    { id: 'm7', cat: 'Kuliner', q: 'Makanan yang paling banyak dikonsumsi manusia di seluruh dunia berdasarkan total berat adalah [...].', a: 'Tebu' },
    { id: 'm8', cat: 'Kuliner', q: 'Di Filipina, ada makanan bernama "balut" yang berupa telur bebek yang sudah dibuahi dan berisi [...].', a: 'Janin Bebek yang Sudah Berkembang Sebagian' },
    { id: 'm9', cat: 'Kuliner', q: 'Honey (madu) bisa dimanfaatkan sebagai [...] pada luka karena sifat antibakterinya.', a: 'Balutan Luka' },
    { id: 'm10', cat: 'Kuliner', q: 'Di Jepang, ada vending machine yang menjual [...] hangat dalam kaleng.', a: 'Telur Rebus' },
    { id: 'm11', cat: 'Kuliner', q: 'Kentang goreng (French Fries) sebenarnya berasal dari [...], bukan dari Perancis seperti namanya.', a: 'Belgia' },
    { id: 'm12', cat: 'Kuliner', q: 'Roti croissant yang identik dengan Perancis sebenarnya pertama kali diciptakan di [...].', a: 'Austria' },
    { id: 'm13', cat: 'Kuliner', q: 'Makanan "Sushi" awalnya bukanlah makanan yang kita kenal sekarang — sushi kuno adalah [...] yang difermentasi dalam nasi.', a: 'Ikan yang Diawetkan dengan Nasi' },
    { id: 'm14', cat: 'Kuliner', q: 'Jelly Bean (kacang jeli) pertama kali dikirimkan ke [...] sebagai hadiah selama Perang Saudara Amerika.', a: 'Tentara Konfederasi di Medan Perang' },
    { id: 'm15', cat: 'Kuliner', q: 'Buah tomat yang kita anggap sayuran sebenarnya secara botani adalah [...].', a: 'Buah' },
    { id: 'm16', cat: 'Kuliner', q: 'Kacang tanah (peanut butter) pertama kali dipatenkan oleh [...] bukan oleh George Washington Carver.', a: 'Marcellus Gilmore Edson' },
    { id: 'm17', cat: 'Kuliner', q: 'Makanan fast food McDonald\'s pertama yang dijual adalah [...], bukan burger.', a: 'Hotdog' },
    { id: 'm18', cat: 'Kuliner', q: 'Rasa umami (gurih sedap) pertama kali diisolasi dan dinamai oleh ilmuwan Jepang Kikunae Ikeda dari [...].', a: 'Kaldu Rumput Laut' },
    { id: 'm19', cat: 'Kuliner', q: 'Es krim cone (kerucut) pertama kali diciptakan secara tidak sengaja di World\'s Fair tahun 1904 karena [...].', a: 'Penjual Es Krim Kehabisan Piring dan Penjual Wafer Membantu' },
    { id: 'm20', cat: 'Kuliner', q: 'Jus jeruk pertama kali dipasarkan ke masyarakat luas setelah ditemukan cara membuatnya tidak basi, yaitu dengan proses [...].', a: 'Pasteurisasi dan Penghilangan Oksigen' },
    { id: 'm21', cat: 'Kuliner', q: 'Minuman Coca-Cola pertama kali berwarna [...] sebelum ditambahkan karamel untuk warna gelap.', a: 'Hijau' },
    { id: 'm22', cat: 'Kuliner', q: 'Nutrisi dari wortel paling optimal diserap tubuh ketika wortel [...].', a: 'Dimasak atau Dipotong' },
    { id: 'm23', cat: 'Kuliner', q: 'Di Islandia, ada makanan tradisional bernama "Hákarl" yang merupakan daging hiu yang [...] selama berbulan-bulan.', a: 'Difermentasi' },
    { id: 'm24', cat: 'Kuliner', q: 'Kafein dalam kopi sebenarnya berfungsi sebagai [...] alami pada tanaman kopi untuk mengusir serangga.', a: 'Pestisida Alami' },
    { id: 'm25', cat: 'Kuliner', q: 'Cokelat putih secara teknis bukan cokelat karena tidak mengandung [...].', a: 'Kakao Padat' },
    { id: 'm26', cat: 'Kuliner', q: 'Minuman energi "Red Bull" tidak boleh dijual di [...] negara karena dianggap berbahaya.', a: 'Beberapa Negara Eropa' },
    { id: 'm27', cat: 'Kuliner', q: 'Keju paling mahal di dunia "Pule" dibuat dari susu [...].', a: 'Keledai Balkan' },
    { id: 'm28', cat: 'Kuliner', q: 'Makanan bernama "Century Egg" atau telur seribu tahun dari China sebenarnya hanya difermentasi selama [...].', a: 'Beberapa Minggu hingga Beberapa Bulan' },
    { id: 'm29', cat: 'Kuliner', q: 'Anggur/grape yang digunakan untuk membuat wine terbaik di Eropa dirawat dengan cara [...] yang unik termasuk membuat akarnya "stres".', a: 'Sengaja Tidak Disiram Agar Akar Menggali Lebih Dalam' },
    { id: 'm30', cat: 'Kuliner', q: 'Di Korea, ada tradisi makan mie panjang pada hari ulang tahun yang melambangkan [...].', a: 'Panjang Umur dan Keberuntungan' },
    { id: 'm31', cat: 'Kuliner', q: 'Pisang yang kita makan sekarang berbeda dari pisang tahun 1950-an — varietas lama bernama "[...]" punah karena penyakit jamur.', a: 'Gros Michel' },
    { id: 'm32', cat: 'Kuliner', q: 'Bumbu masak MSG (Monosodium Glutamat) yang sering dituduh berbahaya sebenarnya secara ilmiah terbukti [...] dari garam dapur biasa.', a: 'Tidak Lebih Berbahaya' },
    { id: 'm33', cat: 'Kuliner', q: 'Pizza Hawaii yang kontroversial (topping nanas) pertama kali diciptakan di [...], bukan di Hawaii atau Italia.', a: 'Kanada' },
    { id: 'm34', cat: 'Kuliner', q: 'Makanan paling pedas di dunia berdasarkan skala Scoville adalah cabai bernama [...].', a: 'Pepper X atau Carolina Reaper' },
    { id: 'm35', cat: 'Kuliner', q: 'Air kelapa memiliki komposisi elektrolit yang sangat mirip dengan [...] sehingga pernah digunakan sebagai penggantinya dalam keadaan darurat.', a: 'Plasma Darah' },
    { id: 'm36', cat: 'Kuliner', q: 'Makanan "Foie Gras" yang mahal adalah hati bebek atau angsa yang dibesarkan dengan cara [...] kontroversial.', a: 'Disuapi Paksa' },
    { id: 'm37', cat: 'Kuliner', q: 'Restoran "Noma" di Denmark yang berulang kali dinobatkan sebagai restoran terbaik dunia baru-baru ini [...].', a: 'Menutup Restorannya Secara Permanen' },
    { id: 'm38', cat: 'Kuliner', q: 'Biji kopi "Geisha" dari Ethiopia, yang harganya ratusan dolar per cangkir, pertama kali ditemukan di daerah [...] dan baru populer setelah dibudidayakan di Panama.', a: 'Daerah Gesha, Ethiopia' },
    { id: 'm39', cat: 'Kuliner', q: 'Makanan instan Indomie yang populer pertama kali diluncurkan di Indonesia pada tahun [...].', a: '1972' },
    { id: 'm40', cat: 'Kuliner', q: 'Di Prancis, keju brie yang sudah sangat matang dan berbau tajam justru dianggap [...] dibanding yang masih segar.', a: 'Lebih Berharga' },
    { id: 'm41', cat: 'Kuliner', q: 'Makanan yang mengandung antioksidan tertinggi di dunia, lebih tinggi dari blueberry, adalah [...].', a: 'Cengkeh' },
    { id: 'm42', cat: 'Kuliner', q: 'Bahan makanan "Truffle" yang sangat mahal sulit ditanam secara artifisial karena ia hanya tumbuh dengan bantuan [...].', a: 'Akar Pohon Tertentu' },
    { id: 'm43', cat: 'Kuliner', q: 'Ramen yang kita kenal sebagai makanan Jepang sebenarnya terinspirasi dari masakan [...] yang dibawa imigran ke Jepang.', a: 'China' },
    { id: 'm44', cat: 'Kuliner', q: 'Campuran makanan yang disebut "Miso" adalah pasta fermentasi dari [...] yang bisa difermentasi selama bertahun-tahun.', a: 'Kedelai' },
    { id: 'm45', cat: 'Kuliner', q: 'Makanan yang dinamai "Caesar Salad" bukan dari Julius Caesar — diciptakan oleh seorang restoran Italia di [...] pada tahun 1924.', a: 'Tijuana, Meksiko' },
    { id: 'm46', cat: 'Kuliner', q: 'Di Perancis, ada undang-undang yang mengatur bahwa roti baguette harus dibuat dari bahan-bahan tertentu — tidak boleh mengandung [...].', a: 'Tepung Kedelai atau Aditif Tambahan' },
    { id: 'm47', cat: 'Kuliner', q: 'Mayones (mayonnaise) secara tradisional dibuat hanya dari [...] — tanpa bahan tambahan lain.', a: 'Kuning Telur, Minyak, dan Sedikit Cuka atau Lemon' },
    { id: 'm48', cat: 'Kuliner', q: 'Sarang burung walet (bird\'s nest) yang digunakan dalam sup mahal dibangun dari [...] bukan dari ranting atau daun.', a: 'Air Liur Burung Walet yang Mengeras' },
    { id: 'm49', cat: 'Kuliner', q: 'Di Jepang, warna merah pada daging tuna segar yang mahal akan berubah [...] jika tidak segera didinginkan.', a: 'Kecoklatan' },
    { id: 'm50', cat: 'Kuliner', q: 'Makanan "Kimchi" dari Korea Selatan telah didaftarkan ke UNESCO sebagai [...].', a: 'Warisan Budaya Tak Benda' },
    { id: 'm51', cat: 'Kuliner', q: 'Minyak zaitun extra virgin yang asli seharusnya [...] jika dipanaskan di atas suhu tertentu, berbeda dari minyak sawit.', a: 'Berasap' },
  ],

  sains: [
    { id: 's1', cat: 'Sains', q: 'Jika kamu bisa menghapus semua ruang kosong antar atom dalam tubuh manusia, seluruh umat manusia bisa dipadatkan menjadi sebesar [...].', a: 'Sebuah Gula Batu' },
    { id: 's2', cat: 'Sains', q: 'Waktu tidak berjalan dengan kecepatan yang sama di mana saja — jam di [...] bergerak lebih lambat dibanding di permukaan bumi.', a: 'Dasar Lautan' },
    { id: 's3', cat: 'Sains', q: 'Oksigen cair memiliki warna [...].', a: 'Biru Pucat' },
    { id: 's4', cat: 'Sains', q: 'Air bisa mendidih dan membeku pada suhu yang SAMA dalam kondisi [...].', a: 'Tekanan Triple Point' },
    { id: 's5', cat: 'Sains', q: 'Warna hitam bukan warna cahaya — secara teknis, warna hitam adalah [...].', a: 'Ketiadaan Cahaya' },
    { id: 's6', cat: 'Sains', q: 'Jika kamu jatuh ke lubang hitam, pengamat dari luar akan melihatmu [...] di tepi lubang hitam selamanya.', a: 'Membeku' },
    { id: 's7', cat: 'Sains', q: 'Suhu rata-rata luar angkasa adalah sekitar [...] derajat Celsius.', a: '-270°C' },
    { id: 's8', cat: 'Sains', q: 'Ada lebih banyak kombinasi berbeda dari setumpuk kartu remi (52 kartu) daripada [...] di seluruh alam semesta yang diketahui.', a: 'Jumlah Atom di Bumi' },
    { id: 's9', cat: 'Sains', q: 'Seluruh energi yang dibutuhkan untuk memenuhi konsumsi listrik dunia selama setahun bisa diperoleh dari [...] sinar matahari.', a: '1,5 Jam Sinar Matahari di Bumi' },
    { id: 's10', cat: 'Sains', q: 'Dalam eksperimen terkenal, kucing Schrödinger diusulkan oleh Erwin Schrödinger untuk mengkritik interpretasi [...] dari mekanika kuantum.', a: 'Copenhagen' },
    { id: 's11', cat: 'Sains', q: 'Senyawa kimia vanillin yang memberi aroma vanila bisa disintesis dari [...] sebagai bahan baku alternatif.', a: 'Kotoran Sapi' },
    { id: 's12', cat: 'Sains', q: 'Buah-buahan dan sayuran organik mengandung lebih banyak [...] daripada yang non-organik.', a: 'Pestisida Alami' },
    { id: 's13', cat: 'Sains', q: 'Tubuh manusia mengandung cukup [...] untuk membuat sekitar 900 pensil.', a: 'Karbon' },
    { id: 's14', cat: 'Sains', q: 'Kecepatan cahaya di dalam air lebih [...] dibanding kecepatan cahaya di ruang hampa.', a: 'Lambat' },
    { id: 's15', cat: 'Sains', q: 'Neutron star (bintang neutron) memiliki kepadatan sedemikian rupa sehingga satu sendok teh massanya setara dengan [...].', a: 'Miliaran Ton' },
    { id: 's16', cat: 'Sains', q: 'Atom emas yang kamu pegang hari ini kemungkinan besar pernah berada di dalam [...] miliaran tahun yang lalu.', a: 'Bintang yang Meledak' },
    { id: 's17', cat: 'Sains', q: 'Petir menyambar Bumi sekitar [...] kali setiap detiknya.', a: '100 Kali per Detik' },
    { id: 's18', cat: 'Sains', q: 'Manusia dan pisang berbagi sekitar [...] persen DNA yang sama.', a: '50-60 Persen' },
    { id: 's19', cat: 'Sains', q: 'Telah terbukti secara ilmiah bahwa tanaman dapat "[...]" ketika dirusak — dengan mengirimkan sinyal kimia ke tanaman di sekitarnya.', a: 'Berkomunikasi' },
    { id: 's20', cat: 'Sains', q: 'Material paling keras yang pernah dibuat manusia adalah [...], lebih keras dari intan.', a: 'Wurtzite Boron Nitride atau Lonsdaleite' },
    { id: 's21', cat: 'Sains', q: 'Otak manusia memiliki sekitar [...] neuron — setara dengan jumlah bintang di galaksi Bima Sakti.', a: '86 Miliar Neuron' },
    { id: 's22', cat: 'Sains', q: 'Fenomena "Placebo Effect" terbukti bisa bekerja meskipun pasien [...].', a: 'Tahu Bahwa Mereka Sedang Diberikan Plasebo' },
    { id: 's23', cat: 'Sains', q: 'Gelombang gravitasi pertama kali terdeteksi pada tahun 2015 dan berasal dari tabrakan dua [...] 1,3 miliar tahun yang lalu.', a: 'Lubang Hitam' },
    { id: 's24', cat: 'Sains', q: 'Warna pelangi yang tidak bisa dilihat oleh mata manusia namun ada dalam spektrum sebenarnya adalah [...].', a: 'Inframerah dan Ultraviolet' },
    { id: 's25', cat: 'Sains', q: 'Teori Relativitas Khusus Einstein mengatakan bahwa objek yang bergerak sangat cepat mendekati kecepatan cahaya akan mengalami [...].', a: 'Dilatasi Waktu' },
    { id: 's26', cat: 'Sains', q: 'Virus HIV pada dasarnya adalah [...] yang menyerang sel kekebalan tubuh manusia.', a: 'Retrovirus' },
    { id: 's27', cat: 'Sains', q: 'Lautan menyerap sekitar [...] persen karbon dioksida yang dihasilkan oleh aktivitas manusia.', a: '30 Persen' },
    { id: 's28', cat: 'Sains', q: 'Bumi memiliki inti bagian dalam yang padat terbuat dari [...] yang ukurannya hampir sama dengan Bulan.', a: 'Besi dan Nikel' },
    { id: 's29', cat: 'Sains', q: 'Eksperimen "Double Slit" membuktikan bahwa partikel kuantum bisa melewati dua celah sekaligus seolah ia adalah [...].', a: 'Gelombang' },
    { id: 's30', cat: 'Sains', q: 'Serotonin, hormon kebahagiaan, sebagian besar diproduksi bukan di otak melainkan di [...].', a: 'Usus' },
    { id: 's31', cat: 'Sains', q: 'Api di luar angkasa memiliki bentuk yang berbeda dari di Bumi — ia berbentuk [...] karena tidak ada konveksi udara.', a: 'Bola' },
    { id: 's32', cat: 'Sains', q: 'Proses yang disebut "Quantum Tunneling" memungkinkan partikel untuk [...] dinding penghalang tanpa energi yang cukup.', a: 'Melewati' },
    { id: 's33', cat: 'Sains', q: 'Ada lebih banyak mikroba di dalam tubuh manusia daripada [...] manusia itu sendiri.', a: 'Jumlah Sel Manusianya' },
    { id: 's34', cat: 'Sains', q: 'Reaksi kimia yang membuat besi berkarat disebut oksidasi — proses yang sama yang membuat [...] menghasilkan energi di tubuh.', a: 'Metabolisme Sel' },
    { id: 's35', cat: 'Sains', q: 'Teleskop James Webb yang diluncurkan NASA bisa melihat cahaya dari galaksi yang jaraknya [...] tahun cahaya.', a: '13+ Miliar Tahun Cahaya' },
    { id: 's36', cat: 'Sains', q: 'Kecerdasan buatan (AI) modern sebagian besar didasarkan pada teknik bernama [...] yang meniru cara neuron otak bekerja.', a: 'Neural Network' },
    { id: 's37', cat: 'Sains', q: 'Tubuh manusia sepenuhnya mengganti seluruh sel kulitnya dalam waktu sekitar [...].', a: '2-4 Minggu' },
    { id: 's38', cat: 'Sains', q: 'Fosil manusia modern (Homo sapiens) tertua yang ditemukan berasal dari [...] tahun yang lalu.', a: '300.000 Tahun' },
    { id: 's39', cat: 'Sains', q: 'Teori Big Bang menyatakan alam semesta dimulai sekitar [...] miliar tahun yang lalu dari satu titik yang sangat kecil dan panas.', a: '13,8 Miliar Tahun Lalu' },
    { id: 's40', cat: 'Sains', q: 'Saat kamu melihat bintang di langit malam, kamu sebenarnya melihat cahaya yang meninggalkan bintang tersebut [...] yang lalu.', a: 'Ratusan hingga Ribuan Tahun yang Lalu' },
    { id: 's41', cat: 'Sains', q: 'Obat antibiotik tidak bekerja melawan [...] — hanya bakteri yang bisa ditarget.', a: 'Virus' },
    { id: 's42', cat: 'Sains', q: 'Hukum Termodinamika Kedua menyatakan bahwa entropi (kekacauan) di alam semesta selalu [...] dari waktu ke waktu.', a: 'Meningkat' },
    { id: 's43', cat: 'Sains', q: 'Mineral Fluorapatite yang ditemukan di gigi manusia adalah salah satu zat [...] yang diproduksi tubuh.', a: 'Paling Keras' },
    { id: 's44', cat: 'Sains', q: 'Proses fotosintesis tanaman mengubah CO₂ dan air menjadi glukosa menggunakan [...] sebagai sumber energi.', a: 'Cahaya Matahari' },
    { id: 's45', cat: 'Sains', q: 'Di dalam inti atom, proton dan neutron tersusun dari partikel yang lebih kecil bernama [...].', a: 'Quark' },
    { id: 's46', cat: 'Sains', q: 'Titanium lebih kuat dari baja namun jauh lebih [...].', a: 'Ringan' },
    { id: 's47', cat: 'Sains', q: 'Proses kloning pertama yang berhasil dilakukan pada mamalia menghasilkan seekor domba bernama [...] pada tahun 1996.', a: 'Dolly' },
    { id: 's48', cat: 'Sains', q: 'Kecepatan rata-rata koneksi internet seluruh dunia pada 2024 adalah sekitar [...] Mbps.', a: '100+ Mbps' },
    { id: 's49', cat: 'Sains', q: 'Tubuh manusia mengandung sekitar [...] liter darah.', a: '4,7 hingga 5,5 Liter' },
    { id: 's50', cat: 'Sains', q: 'Elemen kimia yang disebut "Oganesson" (nomor atom 118) adalah elemen terberat dan paling [...] dalam tabel periodik.', a: 'Tidak Stabil' },
    { id: 's51', cat: 'Sains', q: 'Fenomena "Aurora Borealis" (Cahaya Utara) terjadi akibat interaksi antara [...] dan atmosfer Bumi.', a: 'Partikel Angin Matahari dan Medan Magnet Bumi' },
    { id: 's52', cat: 'Sains', q: 'Otak manusia menggunakan sekitar [...] persen dari total energi tubuh meski hanya menyumbang 2% dari berat badan.', a: '20 Persen' },
  ],

  indonesia: [
    { id: 'i1', cat: 'Indonesia', q: 'Indonesia adalah negara dengan [...] terbanyak di dunia.', a: 'Jumlah Pulau' },
    { id: 'i2', cat: 'Indonesia', q: 'Bunga Rafflesia Arnoldii, bunga terbesar di dunia yang mekar di Indonesia, memiliki bau yang menyerupai [...].', a: 'Daging Busuk' },
    { id: 'i3', cat: 'Indonesia', q: 'Bahasa Indonesia memiliki kata "jayus" yang artinya [...] dan sudah masuk ke dalam Oxford English Dictionary.', a: 'Lelucon Garing yang Tidak Lucu Tapi Bikin Ketawa' },
    { id: 'i4', cat: 'Indonesia', q: 'Gunung Tambora di Sumbawa meletus pada tahun 1815 dan menyebabkan seluruh dunia mengalami [...].', a: 'Tahun Tanpa Musim Panas' },
    { id: 'i5', cat: 'Indonesia', q: 'Di Indonesia, terdapat spesies komodo yang hanya hidup di pulau-pulau tertentu NTT. Komodo bisa bereproduksi secara [...] tanpa jantan.', a: 'Partenogenesis' },
    { id: 'i6', cat: 'Indonesia', q: 'Kata "Orangutan" dalam bahasa Melayu/Indonesia secara harfiah berarti [...].', a: 'Manusia Hutan' },
    { id: 'i7', cat: 'Indonesia', q: 'Lagu "Halo-Halo Bandung" diciptakan oleh Ismail Marzuki sebagai respons terhadap peristiwa [...].', a: 'Bandung Lautan Api' },
    { id: 'i8', cat: 'Indonesia', q: 'Kata "gado-gado" dalam bahasa gaul Jakarta lama berarti [...] sebelum akhirnya dipakai sebagai nama makanan.', a: 'Campuran Berbagai Hal' },
    { id: 'i9', cat: 'Indonesia', q: 'Naskah Sumpah Pemuda 1928 yang asli ditulis dengan tangan oleh [...].', a: 'Muhammad Yamin' },
    { id: 'i10', cat: 'Indonesia', q: 'Pita Olimpiade perak (Silver) Indonesia pertama kali diraih dari cabang olahraga [...] di Olimpiade Barcelona 1992.', a: 'Panahan' },
    { id: 'i11', cat: 'Indonesia', q: 'Di Bali, ada tradisi "Ngaben" (kremasi), dan abu jenazah dilarung ke [...] sebagai simbol kembali ke alam.', a: 'Laut' },
    { id: 'i12', cat: 'Indonesia', q: 'Di zaman kerajaan Majapahit, wilayah kekuasaannya mencakup hingga [...] di luar Nusantara.', a: 'Sebagian Malaysia, Filipina, Papua Nugini, dan Thailand Selatan' },
    { id: 'i13', cat: 'Indonesia', q: 'Proklamasi Kemerdekaan Indonesia dibacakan oleh Soekarno pada jam [...] pagi waktu Jakarta.', a: '10.00 WIB' },
    { id: 'i14', cat: 'Indonesia', q: 'Candi Borobudur di Jawa Tengah adalah kuil Buddha terbesar di dunia dan dibangun sekitar tahun [...].', a: '800-an Masehi' },
    { id: 'i15', cat: 'Indonesia', q: 'Suku Baduy di Banten masih hidup secara tradisional dan dilarang menggunakan [...] dalam kehidupan sehari-hari.', a: 'Teknologi Modern, Listrik, Kendaraan' },
    { id: 'i16', cat: 'Indonesia', q: 'Danau Toba di Sumatera Utara adalah danau vulkanik terbesar di dunia — terbentuk dari letusan supervulkan sekitar [...] tahun yang lalu.', a: '74.000 Tahun Lalu' },
    { id: 'i17', cat: 'Indonesia', q: 'Indonesia adalah penghasil [...] terbesar di dunia, komoditas yang sering dijuluki "emas merah".', a: 'Minyak Sawit' },
    { id: 'i18', cat: 'Indonesia', q: 'Wayang kulit merupakan seni pertunjukan bayangan yang telah diakui UNESCO sebagai [...].', a: 'Warisan Budaya Tak Benda Dunia' },
    { id: 'i19', cat: 'Indonesia', q: 'Di Papua, suku Korowai dikenal karena membangun rumah mereka di [...] setinggi puluhan meter.', a: 'Atas Pohon' },
    { id: 'i20', cat: 'Indonesia', q: 'Bahasa Indonesia adalah bahasa yang memiliki penutur asli terbanyak ke-[...] di dunia.', a: 'Ke-10' },
    { id: 'i21', cat: 'Indonesia', q: 'Ritual "Rambu Solo" di Tana Toraja, Sulawesi Selatan adalah upacara pemakaman di mana jenazah bisa disimpan selama [...] sebelum dikuburkan.', a: 'Bertahun-tahun' },
    { id: 'i22', cat: 'Indonesia', q: 'Indonesia memiliki hutan hujan tropis terbesar ke-[...] di dunia setelah Amazon dan Kongo.', a: 'Ketiga' },
    { id: 'i23', cat: 'Indonesia', q: 'Batik Indonesia telah diakui UNESCO sebagai Warisan Dunia pada tahun [...].', a: '2009' },
    { id: 'i24', cat: 'Indonesia', q: 'Gunung Krakatau yang meletus dahsyat pada 1883 menyebabkan suara letusannya terdengar hingga [...].', a: 'Pulau Rodriguez, Mauritius' },
    { id: 'i25', cat: 'Indonesia', q: 'Presiden RI pertama Ir. Soekarno lahir di [...] pada 6 Juni 1901.', a: 'Surabaya, Jawa Timur' },
    { id: 'i26', cat: 'Indonesia', q: 'Ibu Kota baru Indonesia bernama "Nusantara" dibangun di Provinsi [...].', a: 'Kalimantan Timur' },
    { id: 'i27', cat: 'Indonesia', q: 'Indonesia adalah negara kepulauan dengan garis pantai terpanjang [...] di dunia setelah Kanada.', a: 'Kedua' },
    { id: 'i28', cat: 'Indonesia', q: 'Pertandingan sepak bola paling banyak penonton di Indonesia tercatat saat partai antara [...] di stadion Gelora Bung Karno.', a: 'Timnas Indonesia vs Berbagai Lawan' },
    { id: 'i29', cat: 'Indonesia', q: 'Upacara "Ngilu" atau "Potong Jari" sebagai tanda berkabung pernah dipraktekkan oleh suku [...] di Papua.', a: 'Suku Dani' },
    { id: 'i30', cat: 'Indonesia', q: 'Kebun binatang tertua di Indonesia adalah Kebun Binatang Surabaya yang berdiri sejak tahun [...].', a: '1916' },
    { id: 'i31', cat: 'Indonesia', q: 'Festival "Pasola" di Sumba adalah tradisi perang kuda berkuda dengan tombak yang dilakukan untuk [...].', a: 'Merayakan Musim Tanam dan Meminta Berkah Panen' },
    { id: 'i32', cat: 'Indonesia', q: 'Noken, tas rajutan khas Papua yang dibawa di kepala, telah diakui UNESCO sebagai [...].', a: 'Warisan Budaya Tak Benda' },
    { id: 'i33', cat: 'Indonesia', q: 'Indonesia adalah negara dengan populasi Muslim terbesar di dunia dengan sekitar [...] juta Muslim.', a: '230+ Juta Muslim' },
    { id: 'i34', cat: 'Indonesia', q: 'Sate yang terkenal di Indonesia berasal dari pengaruh pedagang Arab yang membawa teknik [...] ke Nusantara.', a: 'Memanggang Daging di Tusuk' },
    { id: 'i35', cat: 'Indonesia', q: 'Pulau Jawa adalah salah satu pulau terpadat di dunia dengan populasi sekitar [...] juta jiwa.', a: '155+ Juta Jiwa' },
    { id: 'i36', cat: 'Indonesia', q: 'Keris adalah senjata tradisional Indonesia yang memiliki [...] bilah bergelombang yang memiliki makna filosofis.', a: 'Bilah Bergerigi' },
    { id: 'i37', cat: 'Indonesia', q: 'Di Bali, ada tradisi "Nyepi" di mana seluruh pulau Bali benar-benar [...] selama 24 jam penuh.', a: 'Sunyi Total' },
    { id: 'i38', cat: 'Indonesia', q: 'Tim bulu tangkis Indonesia pertama kali memenangkan Piala Thomas (beregu putra) pada tahun [...].', a: '1958' },
    { id: 'i39', cat: 'Indonesia', q: 'Suku Bajo di Sulawesi adalah suku pelaut nomaden yang tinggal di [...] dan dikenal memiliki kemampuan menyelam luar biasa.', a: 'Rumah-rumah Terapung di Laut' },
    { id: 'i40', cat: 'Indonesia', q: 'Di Sumatera Barat, sistem kekerabatan masyarakat Minangkabau adalah matrilineal — artinya garis keturunan dan warisan ditentukan dari [...].', a: 'Pihak Ibu' },
    { id: 'i41', cat: 'Indonesia', q: 'Candi Prambanan di Yogyakarta adalah kompleks candi Hindu terbesar di [...].', a: 'Asia Tenggara' },
    { id: 'i42', cat: 'Indonesia', q: 'Tari Saman dari Aceh yang terkenal karena gerakan tangan cepat dan sinkron sudah diakui oleh [...] sebagai warisan dunia.', a: 'UNESCO' },
    { id: 'i43', cat: 'Indonesia', q: 'Konstitusi Indonesia (UUD 1945) menyebutkan bahwa tujuan negara adalah melindungi segenap bangsa dan "memajukan kesejahteraan umum" — ini tertuang dalam [...].', a: 'Pembukaan' },
    { id: 'i44', cat: 'Indonesia', q: 'Kota Samarinda di Kalimantan Timur adalah penghasil [...] terbesar yang pernah ada di Indonesia.', a: 'Batu Bara' },
    { id: 'i45', cat: 'Indonesia', q: 'Seni pertunjukan "Reog Ponorogo" menggunakan topeng berbentuk kepala [...] yang beratnya bisa mencapai 50 kg.', a: 'Singa' },
    { id: 'i46', cat: 'Indonesia', q: 'Bahasa daerah terbanyak yang dimiliki oleh satu negara di dunia adalah milik [...].', a: 'Indonesia' },
    { id: 'i47', cat: 'Indonesia', q: 'TNI (Tentara Nasional Indonesia) didirikan pada tanggal [...] sebagai Tentara Keamanan Rakyat.', a: '5 Oktober 1945' },
    { id: 'i48', cat: 'Indonesia', q: 'Rupiah pertama kali dicetak dan beredar resmi pada tahun [...] sebagai mata uang negara.', a: '1946' },
    { id: 'i49', cat: 'Indonesia', q: 'Di Indonesia, ada tradisi makan bersama tanpa alat makan yang disebut [...] terutama di acara-acara adat Jawa.', a: 'Makan dengan Tangan' },
    { id: 'i50', cat: 'Indonesia', q: 'Kota Yogyakarta adalah satu-satunya daerah istimewa di Indonesia yang kepala pemerintahannya masih dijabat oleh [...].', a: 'Sultan' },
    { id: 'i51', cat: 'Indonesia', q: 'Letak geografis Indonesia berada di Cincin Api Pasifik sehingga memiliki [...] gunung berapi aktif — terbanyak di dunia.', a: '127 Gunung Berapi Aktif' },
    { id: 'i52', cat: 'Indonesia', q: 'Di masa kolonial, tanaman rempah cengkeh dan pala hanya bisa ditemukan di kepulauan [...] di Maluku, menjadikannya rebutan bangsa Eropa.', a: 'Kepulauan Banda dan Maluku' },
  ],

  bisnis: [
    { id: 'biz1', cat: 'Bisnis', q: 'Apple Inc. pernah hampir bangkrut pada tahun 1997, dan diselamatkan oleh investasi dari [...].', a: 'Microsoft' },
    { id: 'biz2', cat: 'Bisnis', q: 'Coca-Cola formula aslinya mengandung [...] sebagai bahan aktif hingga tahun 1903.', a: 'Kokain' },
    { id: 'biz3', cat: 'Bisnis', q: 'IKEA sebagai merek furnitur ternyata nama "IKEA" merupakan singkatan dari [...].', a: 'Ingvar Kamprad Elmtaryd Agunnaryd' },
    { id: 'biz4', cat: 'Bisnis', q: 'Jeff Bezos, pendiri Amazon, memulai perusahaannya dari [...] pada tahun 1994.', a: 'Garasi Rumahnya di Bellevue, Washington' },
    { id: 'biz5', cat: 'Bisnis', q: 'Nokia, perusahaan yang kini dikenal sebagai pembuat ponsel, awalnya adalah perusahaan pembuat [...].', a: 'Kertas dan Karet' },
    { id: 'biz6', cat: 'Bisnis', q: 'Starbucks mendapatkan namanya dari karakter [...] dalam novel Moby Dick.', a: 'Starbuck' },
    { id: 'biz7', cat: 'Bisnis', q: 'Walmart mempekerjakan lebih banyak orang daripada populasi seluruh negara [...].', a: 'Panama atau Norwegia' },
    { id: 'biz8', cat: 'Bisnis', q: 'Amazon menghasilkan lebih banyak uang dari layanan cloud-nya (AWS) daripada dari [...] seluruh bisnisnya.', a: 'Penjualan Ritel E-Commerce' },
    { id: 'biz9', cat: 'Bisnis', q: 'Harga satu tiket Original Disneyland pada tahun pembukaannya tahun 1955 adalah [...] dolar.', a: '$1' },
    { id: 'biz10', cat: 'Bisnis', q: 'Negara dengan GDP terkecil di dunia adalah [...], yang ekonominya lebih kecil dari toko supermarket besar.', a: 'Nauru' },
    { id: 'biz11', cat: 'Bisnis', q: 'Brand Lamborghini didirikan oleh Ferruccio Lamborghini yang awalnya berbisnis membuat [...], bukan mobil sport.', a: 'Traktor Pertanian' },
    { id: 'biz12', cat: 'Bisnis', q: 'Perusahaan Nintendo hampir bangkrut pada [...] sebelum akhirnya menciptakan Game Boy dan diselamatkan.', a: 'Awal 1980-an' },
    { id: 'biz13', cat: 'Bisnis', q: 'Logo Nike "Swoosh" dibuat oleh mahasiswi desain bernama Carolyn Davidson yang dibayar hanya [...] pada tahun 1971.', a: '$35' },
    { id: 'biz14', cat: 'Bisnis', q: 'Merk Adidas dinamai oleh pendirinya Adolf "Adi" Dassler — sementara saudaranya mendirikan [...] yang menjadi pesaing.', a: 'PUMA' },
    { id: 'biz15', cat: 'Bisnis', q: 'Perusahaan yang pertama kali menciptakan dan menjual komputer pribadi (PC) untuk konsumen umum bukanlah Apple, melainkan [...].', a: 'MITS Altair 8800' },
    { id: 'biz16', cat: 'Bisnis', q: 'Elon Musk, orang terkaya di dunia, tidak memiliki [...] — sebuah hal yang tidak biasa untuk orang sekaya dia.', a: 'Rumah Permanen' },
    { id: 'biz17', cat: 'Bisnis', q: 'YouTube pertama kali dibuat sebagai platform [...] sebelum akhirnya diubah menjadi platform video umum.', a: 'Kencan Online' },
    { id: 'biz18', cat: 'Bisnis', q: 'Google Inc. awalnya bernama "[...]" sebelum diubah menjadi Google.', a: 'BackRub' },
    { id: 'biz19', cat: 'Bisnis', q: 'Harga saham Amazon saat pertama kali IPO (penawaran umum perdana) pada tahun 1997 adalah [...] per lembar.', a: '$18 Per Lembar' },
    { id: 'biz20', cat: 'Bisnis', q: 'Perusahaan yang memproduksi Nutella, Ferrero, mengonsumsi [...] dari total produksi hazelnut dunia setiap tahunnya.', a: '25-30 Persen' },
    { id: 'biz21', cat: 'Bisnis', q: 'Merek fashion Gucci didirikan oleh Guccio Gucci yang awalnya bekerja sebagai [...] di London.', a: 'Bellboy' },
    { id: 'biz22', cat: 'Bisnis', q: 'Perusahaan Sony awalnya bernama "[...]" dan produk pertamanya adalah selimut panas elektrik.', a: 'Tokyo Tsushin Kogyo' },
    { id: 'biz23', cat: 'Bisnis', q: 'Facebook (Meta) pertama kali hanya bisa diakses oleh mahasiswa [...] sebelum akhirnya dibuka untuk umum.', a: 'Harvard University' },
    { id: 'biz24', cat: 'Bisnis', q: 'Perusahaan 3M, yang terkenal dengan Post-it Note dan Scotch Tape, awalnya adalah perusahaan tambang [...] yang gagal.', a: 'Korundum' },
    { id: 'biz25', cat: 'Bisnis', q: 'Seorang penemu tidak dikenal menjual paten untuk mesin ATM pertama seharga hanya [...] dan menyerahkan seluruh hak patennya.', a: '$1' },
    { id: 'biz26', cat: 'Bisnis', q: 'Merek mewah Louis Vuitton awalnya hanya membuat [...] sebelum berkembang ke fashion dan aksesori.', a: 'Koper Perjalanan' },
    { id: 'biz27', cat: 'Bisnis', q: 'McDonald\'s menghasilkan lebih banyak pendapatan dari bisnis [...] daripada dari penjualan burger itu sendiri.', a: 'Real Estate' },
    { id: 'biz28', cat: 'Bisnis', q: 'Perusahaan Blackberry, yang mendominasi smartphone sebelum iPhone, kehilangan 95% nilai sahamnya karena gagal berinovasi terutama soal [...].', a: 'Layar Sentuh dan Ekosistem Aplikasi' },
    { id: 'biz29', cat: 'Bisnis', q: 'Bill Gates pernah menjadi orang terkaya di dunia selama lebih dari 20 tahun — dia akhirnya turun peringkat setelah [...].', a: 'Banyak Menyumbang ke Yayasan Bill & Melinda Gates' },
    { id: 'biz30', cat: 'Bisnis', q: 'Merek Rolex tidak menjual jam langsung ke konsumen dan tidak punya toko online resmi karena mereka [...].', a: 'Mengontrol Ketat Distribusi lewat Dealer Terakreditasi' },
    { id: 'biz31', cat: 'Bisnis', q: 'Perusahaan PayPal awalnya didirikan dengan nama "[...]" sebelum berganti nama.', a: 'Confinity' },
    { id: 'biz32', cat: 'Bisnis', q: 'Paten untuk teknologi GPS awalnya dipegang oleh [...] dan diberikan secara gratis ke publik pada tahun 2000.', a: 'Departemen Pertahanan Amerika Serikat' },
    { id: 'biz33', cat: 'Bisnis', q: 'Burger King, rival utama McDonald\'s, pernah berganti nama menjadi [...] di Australia karena ada toko lokal yang sudah mendaftarkan nama tersebut.', a: 'Hungry Jack\'s' },
    { id: 'biz34', cat: 'Bisnis', q: 'Perusahaan Netflix awalnya berbisnis sebagai layanan [...] sebelum beralih ke streaming digital.', a: 'Sewa DVD Lewat Pos' },
    { id: 'biz35', cat: 'Bisnis', q: 'Toko online Alibaba didirikan oleh Jack Ma, mantan guru bahasa Inggris yang [...] sebelum mendirikan perusahaan itu.', a: 'Pernah Ditolak 30 Kali Lamaran Kerja Termasuk oleh KFC' },
    { id: 'biz36', cat: 'Bisnis', q: 'Perusahaan Lego hampir bangkrut pada tahun 2003 dan diselamatkan dengan cara [...].', a: 'Memotong Lini Produk, Fokus ke Kolaborasi Film dan Game' },
    { id: 'biz37', cat: 'Bisnis', q: 'Pendiri Snapchat Evan Spiegel pernah menolak tawaran akuisisi dari Facebook senilai [...] miliar dolar.', a: '3 Miliar Dolar' },
    { id: 'biz38', cat: 'Bisnis', q: 'Perusahaan teknologi pertama yang mencapai valuasi 1 triliun dolar adalah [...].', a: 'Apple' },
    { id: 'biz39', cat: 'Bisnis', q: 'Gaji CEO tertinggi dalam sejarah korporat Amerika diterima oleh Elon Musk dari Tesla senilai [...] miliar dolar.', a: 'Paket Kompensasi Kontroversial 56 Miliar Dolar' },
    { id: 'biz40', cat: 'Bisnis', q: 'Red Bull tidak memproduksi minuman energinya sendiri — semuanya diproduksi oleh perusahaan [...] Austria bernama Rauch.', a: 'Perusahaan Minuman Kontrak' },
    { id: 'biz41', cat: 'Bisnis', q: 'Toko H&M (Hennes & Mauritz) pertama kali menjual hanya [...] — bukan pakaian pria atau aksesori.', a: 'Pakaian Wanita' },
    { id: 'biz42', cat: 'Bisnis', q: 'Perusahaan Airbnb didirikan ketika para pendirinya kesulitan membayar sewa dan memutuskan untuk menyewakan [...] di apartemen mereka.', a: 'Kasur Tiup' },
    { id: 'biz43', cat: 'Bisnis', q: 'Investor pertama yang menyuntikkan dana ke Uber adalah [...] yang menginvestasikan $200.000 di tahun 2009.', a: 'Jason Calcanis' },
    { id: 'biz44', cat: 'Bisnis', q: 'Perusahaan Dior dan Louis Vuitton dimiliki oleh group perusahaan yang sama bernama [...].', a: 'LVMH' },
    { id: 'biz45', cat: 'Bisnis', q: 'Perusahaan Berkshire Hathaway milik Warren Buffett awalnya adalah perusahaan [...] sebelum diubah menjadi holding company investasi.', a: 'Tekstil' },
    { id: 'biz46', cat: 'Bisnis', q: 'CEO terlama yang pernah memimpin sebuah perusahaan Fortune 500 adalah [...] yang menjabat selama 60 tahun.', a: 'William Wrigley Jr.' },
    { id: 'biz47', cat: 'Bisnis', q: 'Brand Zara (Inditex) dikenal karena model bisnis "fast fashion" yang mampu membawa tren dari runway ke toko dalam waktu hanya [...] minggu.', a: '2 Minggu' },
    { id: 'biz48', cat: 'Bisnis', q: 'Pendiri perusahaan Dyson (merek vacuum cleaner), James Dyson, membuat [...] prototipe yang gagal sebelum akhirnya berhasil.', a: '5.127 Prototipe' },
    { id: 'biz49', cat: 'Bisnis', q: 'Perusahaan Spotify didirikan di [...] dan go public di New York Stock Exchange pada tahun 2018.', a: 'Stockholm, Swedia' },
    { id: 'biz50', cat: 'Bisnis', q: 'Merk Toyota berasal dari nama keluarga "Toyoda" — nama diubah karena secara karakter kanji Jepang, "Toyota" hanya membutuhkan [...] goresan.', a: '8 Goresan' },
    { id: 'biz51', cat: 'Bisnis', q: 'Perusahaan Disney pernah menolak untuk menjual mainan berlisensi film "Star Wars" — hingga George Lucas [...] hak merchandise-nya.', a: 'Meminta Hak Merchandising Sendiri sebagai Bagian Kontrak' },
  ],

  luar_angkasa: [
    { id: 'la1', cat: 'Luar Angkasa', q: 'Luar angkasa berbau seperti [...] menurut para astronot yang pernah keluar dari ISS.', a: 'Steak Bakar' },
    { id: 'la2', cat: 'Luar Angkasa', q: 'Di planet Mars, satu hari lebih panjang dari Bumi hanya selama [...] menit.', a: '39 Menit 35 Detik' },
    { id: 'la3', cat: 'Luar Angkasa', q: 'Jika dua keping logam yang sama ditempelkan satu sama lain di luar angkasa, mereka akan [...] secara permanen.', a: 'Menyatu' },
    { id: 'la4', cat: 'Luar Angkasa', q: 'Bulan kita bergerak semakin jauh dari Bumi setiap tahun sejauh [...] cm.', a: '3,8 cm per Tahun' },
    { id: 'la5', cat: 'Luar Angkasa', q: 'Ada "awan" di luar angkasa yang mengandung [...] dalam jumlah masif, cukup untuk membuat bir senilai 400 septillion botol.', a: 'Etil Alkohol' },
    { id: 'la6', cat: 'Luar Angkasa', q: 'Astronot yang tinggal di ISS terlalu lama akan [...] setelah kembali ke Bumi karena otot-ototnya melemah.', a: 'Tidak Bisa Berjalan' },
    { id: 'la7', cat: 'Luar Angkasa', q: 'Planet Uranus berputar miring sehingga kutubnya menghadap matahari — artinya satu musim di Uranus berlangsung selama [...].', a: '21 Tahun Bumi' },
    { id: 'la8', cat: 'Luar Angkasa', q: 'Galaksi Andromeda sedang bergerak menuju Milky Way dan diperkirakan akan bertabrakan dalam [...] miliar tahun.', a: '4,5 Miliar Tahun' },
    { id: 'la9', cat: 'Luar Angkasa', q: 'Matahari kita akan berubah menjadi [...] dalam sekitar 5 miliar tahun.', a: 'Red Giant' },
    { id: 'la10', cat: 'Luar Angkasa', q: 'Di planet Venus, satu hari Venus lebih panjang dari satu tahun Venus, karena [...].', a: 'Venus Berotasi Lebih Lambat dari Revolusinya Mengelilingi Matahari' },
    { id: 'la11', cat: 'Luar Angkasa', q: 'Wahana luar angkasa Voyager 1 yang diluncurkan NASA pada 1977 sudah melewati batas Tata Surya dan kini berada di [...].', a: 'Ruang Antarbintang' },
    { id: 'la12', cat: 'Luar Angkasa', q: 'Di permukaan planet Merkurius, suhu bisa mencapai 430°C di siang hari dan turun menjadi -180°C di malam hari karena [...].', a: 'Tidak Memiliki Atmosfer yang Bisa Menyimpan Panas' },
    { id: 'la13', cat: 'Luar Angkasa', q: 'Setiap tahun, sekitar [...] ton material meteor jatuh ke Bumi dalam bentuk debu dan meteorit kecil.', a: '48.000 Ton' },
    { id: 'la14', cat: 'Luar Angkasa', q: 'Jika Matahari digantikan dengan lubang hitam berukuran sama, Bumi tidak akan langsung tersedot — orbit Bumi akan [...].', a: 'Tetap Sama' },
    { id: 'la15', cat: 'Luar Angkasa', q: 'Sabuk Asteroid antara Mars dan Jupiter mengandung lebih dari satu juta asteroid, namun total massanya hanya sekitar [...] dari massa Bulan.', a: '4 Persen Massa Bulan' },
    { id: 'la16', cat: 'Luar Angkasa', q: 'Manusia pertama yang berjalan di Bulan, Neil Armstrong, membawa bersama ke Bulan [...] sebagai kenang-kenangan.', a: 'Sepotong Kecil Kayu dan Kain dari Pesawat Wright Bersaudara' },
    { id: 'la17', cat: 'Luar Angkasa', q: 'Planet Jupiter memiliki badai bernama "Great Red Spot" yang sudah berlangsung lebih dari [...] tahun tanpa berhenti.', a: '350+ Tahun' },
    { id: 'la18', cat: 'Luar Angkasa', q: 'Atmosfer Venus mengandung awan [...] yang membuatnya sangat terang terlihat dari Bumi.', a: 'Asam Sulfat' },
    { id: 'la19', cat: 'Luar Angkasa', q: 'Ada sebuah planet di luar Tata Surya yang diperkirakan seluruh permukaannya tertutup oleh [...] karena tekanan dan suhunya yang ekstrem.', a: 'Berlian Cair' },
    { id: 'la20', cat: 'Luar Angkasa', q: 'ISS (International Space Station) mengorbit Bumi setiap [...] menit sekali dengan kecepatan 28.000 km/jam.', a: '90 Menit' },
    { id: 'la21', cat: 'Luar Angkasa', q: 'Satelit buatan pertama yang diluncurkan ke orbit Bumi adalah [...] milik Uni Soviet pada tahun 1957.', a: 'Sputnik 1' },
    { id: 'la22', cat: 'Luar Angkasa', q: 'Bintang Betelgeuse yang bisa kita lihat di konstelasi Orion diperkirakan akan meledak menjadi supernova yang bisa terlihat siang hari dalam [...] tahun ke depan.', a: 'Ratusan Ribu Tahun' },
    { id: 'la23', cat: 'Luar Angkasa', q: 'Peneliti menemukan bahwa di bulan Saturnus bernama Enceladus, ada [...] yang menyembur dari bawah es di kutub selatan.', a: 'Air Cair' },
    { id: 'la24', cat: 'Luar Angkasa', q: 'Nama "planet" yang berasal dari bahasa Yunani berarti [...] karena benda langit ini bergerak terhadap bintang-bintang lain.', a: '"Pengembara"' },
    { id: 'la25', cat: 'Luar Angkasa', q: 'Teleskop luar angkasa Hubble, yang sudah beroperasi sejak 1990, sebenarnya awalnya memiliki [...] yang rusak dan harus diperbaiki oleh astronot.', a: 'Cermin Utama yang Cacat' },
    { id: 'la26', cat: 'Luar Angkasa', q: 'Suara tidak bisa merambat di luar angkasa karena [...].', a: 'Tidak Ada Medium' },
    { id: 'la27', cat: 'Luar Angkasa', q: 'Planet Neptun, paling jauh dalam Tata Surya, pertama kali ditemukan bukan dengan teleskop melainkan dengan [...].', a: 'Kalkulasi Matematika' },
    { id: 'la28', cat: 'Luar Angkasa', q: 'Di Mars, terdapat gunung berapi bernama Olympus Mons yang merupakan [...] di seluruh Tata Surya.', a: 'Gunung Tertinggi' },
    { id: 'la29', cat: 'Luar Angkasa', q: 'Wahana roket SpaceX Falcon 9 milik Elon Musk revolusioner karena mampu [...] setelah meluncurkan satelit ke orbit.', a: 'Mendarat Kembali Secara Vertikal dan Bisa Digunakan Ulang' },
    { id: 'la30', cat: 'Luar Angkasa', q: 'Saat astronot menangis di luar angkasa, air matanya tidak [...] karena tidak ada gravitasi.', a: 'Jatuh ke Bawah' },
    { id: 'la31', cat: 'Luar Angkasa', q: 'Pluto diturunkan statusnya dari planet menjadi "planet kerdil" pada tahun [...] oleh International Astronomical Union.', a: '2006' },
    { id: 'la32', cat: 'Luar Angkasa', q: 'Di dalam lubang hitam, semua materi dan informasi ditekan ke titik tak terhingga yang disebut [...].', a: 'Singularitas' },
    { id: 'la33', cat: 'Luar Angkasa', q: 'Wahana luar angkasa New Horizons yang melewati Pluto pada 2015 membutuhkan [...] tahun perjalanan dari Bumi.', a: '9,5 Tahun' },
    { id: 'la34', cat: 'Luar Angkasa', q: 'Cincin Saturnus yang ikonik sebagian besar tersusun dari [...] dan bukan benda padat.', a: 'Es' },
    { id: 'la35', cat: 'Luar Angkasa', q: 'Setelah astronot China berlanding di Bulan, mereka berencana mendirikan [...] permanen di sana.', a: 'Pangkalan Bulan' },
    { id: 'la36', cat: 'Luar Angkasa', q: 'Misi Apollo 13 yang terkenal hampir berakhir tragis ketika tangki [...] meledak di tengah perjalanan ke Bulan.', a: 'Oksigen' },
    { id: 'la37', cat: 'Luar Angkasa', q: 'Di luar angkasa, jika darah mengalir keluar dari tubuh, darah tersebut akan [...] karena tekanan rendah.', a: 'Langsung Mendidih dan Menguap' },
    { id: 'la38', cat: 'Luar Angkasa', q: 'Seluruh Tata Surya kita mengitari pusat galaksi Bima Sakti sekali dalam waktu sekitar [...] juta tahun.', a: '225-250 Juta Tahun' },
    { id: 'la39', cat: 'Luar Angkasa', q: 'Di permukaan Bulan, jejak kaki astronot Apollo akan bertahan selama [...] tanpa terganggu.', a: 'Jutaan Tahun' },
    { id: 'la40', cat: 'Luar Angkasa', q: 'Bintang neutron yang berputar sangat cepat dan memancarkan sinyal radio disebut [...].', a: 'Pulsar' },
    { id: 'la41', cat: 'Luar Angkasa', q: 'Fenomena "Dark Energy" yang mendorong alam semesta mengembang lebih cepat ditemukan pada tahun [...] dan membuat para ilmuwan terkejut.', a: '1998' },
    { id: 'la42', cat: 'Luar Angkasa', q: 'Bulan-bulan Jupiter yang terbesar disebut "Galilean Moons" karena ditemukan oleh Galileo Galilei — ada [...] buah.', a: '4 Buah' },
    { id: 'la43', cat: 'Luar Angkasa', q: 'Jika kamu berdiri di permukaan Bulan dan melihat ke arah Bumi, Bumi terlihat [...] kali lebih besar dari Bulan yang terlihat dari Bumi.', a: '4 Kali Lebih Besar' },
    { id: 'la44', cat: 'Luar Angkasa', q: 'Konstelasi bintang yang kita kenal seperti Orion dan Scorpius sebenarnya bukan kelompok bintang yang [...] — mereka hanya tampak berdekatan dari sudut pandang Bumi.', a: 'Berdekatan Satu Sama Lain' },
    { id: 'la45', cat: 'Luar Angkasa', q: 'Program luar angkasa Artemis NASA bertujuan untuk mengembalikan manusia ke Bulan untuk pertama kalinya sejak [...].', a: '1972' },
    { id: 'la46', cat: 'Luar Angkasa', q: 'Planet terpanas di Tata Surya bukan Merkurius yang paling dekat ke Matahari, melainkan [...].', a: 'Venus' },
    { id: 'la47', cat: 'Luar Angkasa', q: 'Alam semesta terus mengembang dengan kecepatan yang semakin meningkat — pada akhirnya galaksi-galaksi lain akan [...] dari pengamatan kita.', a: 'Menghilang' },
    { id: 'la48', cat: 'Luar Angkasa', q: 'Bulan Europa milik Jupiter kemungkinan besar memiliki [...] di bawah lapisan esnya.', a: 'Samudra Air Cair' },
    { id: 'la49', cat: 'Luar Angkasa', q: 'Cahaya dari Matahari membutuhkan waktu sekitar [...] menit untuk sampai ke Bumi.', a: '8 Menit 20 Detik' },
    { id: 'la50', cat: 'Luar Angkasa', q: 'Di tahun 2029, asteroid raksasa bernama "[...]" akan melewati Bumi lebih dekat dari beberapa satelit yang mengorbit.', a: 'Apophis' },
  ],

  gelap: [
    { id: 'g1', cat: 'Psikologi Gelap', q: 'Dalam psikologi, "efek Dunning-Kruger" menggambarkan fenomena di mana orang yang [...] merasa paling percaya diri.', a: 'Paling Tidak Kompeten' },
    { id: 'g2', cat: 'Psikologi Gelap', q: 'Eksperimen Stanford Prison (1971) dihentikan lebih awal karena [...].', a: 'Peserta yang Berperan sebagai "Penjaga" Mulai Menyiksa Sesungguhnya' },
    { id: 'g3', cat: 'Psikologi Gelap', q: 'Dalam eksperimen Milgram tentang ketaatan, hampir [...] persen peserta bersedia memberikan sengatan listrik mematikan karena diperintah.', a: '65 Persen' },
    { id: 'g4', cat: 'Psikologi Gelap', q: '"Bystander Effect" terjadi ketika seseorang tidak menolong korban karena [...].', a: 'Merasa Ada Orang Lain yang Akan Menolong' },
    { id: 'g5', cat: 'Psikologi Gelap', q: 'Seseorang yang terlalu sering berbohong akhirnya mulai [...] tanpa disadari.', a: 'Mempercayai Kebohongannya Sendiri' },
    { id: 'g6', cat: 'Psikologi Gelap', q: 'Stockholm Syndrome — kondisi di mana korban simpati pada penyandera — pertama kali diidentifikasi dalam kasus penyanderaan bank di [...].', a: 'Stockholm, Swedia' },
    { id: 'g7', cat: 'Psikologi Gelap', q: '"Gas Lighting" sebagai istilah manipulasi psikologis berasal dari [...].', a: 'Film' },
    { id: 'g8', cat: 'Psikologi Gelap', q: 'Penelitian menunjukkan bahwa rata-rata manusia berbohong sebanyak [...] kali per hari.', a: '1 hingga 2 Kali per Hari' },
    { id: 'g9', cat: 'Psikologi Gelap', q: 'Fenomena "Folie à Deux" adalah kondisi medis di mana [...].', a: 'Dua Orang Berbagi Delusi' },
    { id: 'g10', cat: 'Psikologi Gelap', q: 'Mimpi buruk yang paling umum dialami manusia di seluruh dunia adalah tentang [...].', a: 'Dikejar atau Terjatuh' },
    { id: 'g11', cat: 'Psikologi Gelap', q: 'Serangan panik sering disalahartikan sebagai serangan jantung karena [...].', a: 'Gejalanya Hampir Identik' },
    { id: 'g12', cat: 'Psikologi Gelap', q: 'Dalam kondisi tertentu, manusia bisa mengalami "Truman Show Delusion" — keyakinan bahwa [...].', a: 'Hidupnya Disiarkan di TV' },
    { id: 'g13', cat: 'Psikologi Gelap', q: '"Dark Triad" dalam psikologi kepribadian merujuk pada tiga sifat berbahaya: Narsisme, Psikopati, dan [...].', a: 'Machiavellianisme' },
    { id: 'g14', cat: 'Psikologi Gelap', q: 'Efek "Broken Windows Theory" menyatakan bahwa lingkungan yang rusak dan tidak terawat [...] perilaku kriminal.', a: 'Mendorong' },
    { id: 'g15', cat: 'Psikologi Gelap', q: 'Penelitian menunjukkan bahwa wajah yang [...] cenderung lebih dipercaya oleh orang lain meski tidak ada korelasi dengan kejujuran.', a: 'Simetris' },
    { id: 'g16', cat: 'Psikologi Gelap', q: '"Solomon Asch Conformity Experiment" membuktikan bahwa sebagian besar orang akan [...] meskipun jawabannya jelas salah.', a: 'Mengikuti Pendapat Kelompok' },
    { id: 'g17', cat: 'Psikologi Gelap', q: 'Fenomena "Cognitive Dissonance" terjadi ketika seseorang memegang dua kepercayaan yang saling bertentangan dan akhirnya [...].', a: 'Merasionalisasi Salah Satunya agar Tidak Merasa Tidak Nyaman' },
    { id: 'g18', cat: 'Psikologi Gelap', q: 'Teknik "Love Bombing" yang sering digunakan oleh manipulator adalah membanjiri target dengan [...] secara berlebihan di awal hubungan.', a: 'Perhatian, Pujian, dan Afeksi' },
    { id: 'g19', cat: 'Psikologi Gelap', q: '"Learned Helplessness" — kondisi pasrah total — pertama kali ditemukan dalam percobaan pada [...] yang terus diberi kejutan listrik tanpa bisa kabur.', a: 'Anjing' },
    { id: 'g20', cat: 'Psikologi Gelap', q: 'Psikopat secara klinis tidak merasakan [...] — area otak amigdala mereka tidak merespons isyarat rasa takut dan empati.', a: 'Empati dan Rasa Bersalah' },
    { id: 'g21', cat: 'Psikologi Gelap', q: '"Semua orang memiliki potensi untuk berbuat jahat dalam kondisi yang tepat" adalah premis dari eksperimen psikologis bernama [...].', a: 'Stanford Prison Experiment' },
    { id: 'g22', cat: 'Psikologi Gelap', q: 'Fenomena "Moral Licensing" terjadi ketika seseorang yang baru saja melakukan kebaikan merasa [...] setelahnya.', a: 'Bebas' },
    { id: 'g23', cat: 'Psikologi Gelap', q: 'Kecanduan media sosial secara neurologis mirip dengan kecanduan [...] karena mengaktifkan sistem reward dopamin yang sama.', a: 'Narkoba' },
    { id: 'g24', cat: 'Psikologi Gelap', q: 'Teknik interogasi "Reid Technique" yang umum digunakan polisi terbukti meningkatkan risiko [...] dari tersangka yang tidak bersalah.', a: 'Pengakuan Palsu' },
    { id: 'g25', cat: 'Psikologi Gelap', q: 'Dalam kondisi psikologis yang disebut "Deindividuation", seseorang dalam kerumunan cenderung lebih mudah melakukan [...] yang tidak akan dilakukan saat sendirian.', a: 'Tindakan Kekerasan atau Pelanggaran Norma' },
    { id: 'g26', cat: 'Psikologi Gelap', q: '"Trolley Problem" adalah dilema etika filosofis di mana kamu harus memilih antara [...] untuk menyelamatkan lebih banyak orang.', a: 'Membunuh Satu Orang atau Membiarkan Lima Orang Mati' },
    { id: 'g27', cat: 'Psikologi Gelap', q: 'Orang yang mengalami trauma berat terkadang tidak ingat kejadiannya sama sekali — mekanisme ini disebut [...] oleh psikolog.', a: 'Dissociative Amnesia' },
    { id: 'g28', cat: 'Psikologi Gelap', q: 'Penelitian tentang "Implicit Bias" menunjukkan bahwa hampir semua orang memiliki [...] terhadap kelompok tertentu meski tidak menyadarinya.', a: 'Prasangka' },
    { id: 'g29', cat: 'Psikologi Gelap', q: 'Fenomena "Terror Management Theory" menyatakan sebagian besar perilaku manusia dimotivasi oleh ketakutan bawah sadar terhadap [...].', a: 'Kematian' },
    { id: 'g30', cat: 'Psikologi Gelap', q: 'Di penjara, penelitian menunjukkan bahwa sel isolasi (solitary confinement) bisa menyebabkan [...] permanen pada narapidana.', a: 'Kerusakan Psikologis' },
    { id: 'g31', cat: 'Psikologi Gelap', q: 'Ilusi "False Memory" yang ditanam oleh Elizabeth Loftus membuktikan bahwa [...] bisa membuat orang "mengingat" hal yang tidak pernah terjadi.', a: 'Pertanyaan yang Menyesatkan' },
    { id: 'g32', cat: 'Psikologi Gelap', q: 'Psikolog menemukan bahwa ketika orang sendirian dalam gelap, sebagian besar mengalami [...] dalam beberapa menit.', a: 'Halusinasi Ringan' },
    { id: 'g33', cat: 'Psikologi Gelap', q: 'Fenomena "Uncanny Valley" adalah rasa tidak nyaman yang dirasakan orang saat melihat robot atau CGI yang [...].', a: 'Hampir Tapi Tidak Cukup Mirip Manusia' },
    { id: 'g34', cat: 'Psikologi Gelap', q: 'Orang yang pernah mengalami near-death experience (NDE) sering melaporkan melihat [...] yang serupa di seluruh dunia meski berbeda budaya.', a: 'Cahaya Terang di Ujung Terowongan' },
    { id: 'g35', cat: 'Psikologi Gelap', q: 'Penelitian "Robbers Cave Experiment" membuktikan bahwa perpecahan kelompok dan konflik antargolongan bisa diciptakan hanya dengan [...].', a: 'Memisahkan Anak-anak ke Dua Kelompok yang Bersaing' },
    { id: 'g36', cat: 'Psikologi Gelap', q: '"Deathbed Phenomenon" adalah kondisi di mana orang sekarat sering mengaku melihat atau berbicara dengan [...] sebelum meninggal.', a: 'Kerabat yang Sudah Meninggal atau Sosok Tak Dikenal' },
    { id: 'g37', cat: 'Psikologi Gelap', q: 'Manusia memiliki kecenderungan alami untuk percaya bahwa hal buruk tidak akan terjadi pada mereka — disebut [...].', a: 'Optimism Bias' },
    { id: 'g38', cat: 'Psikologi Gelap', q: 'Dalam kondisi yang disebut "Capgras Delusion", seseorang yakin bahwa orang yang mereka cintai telah digantikan oleh [...].', a: 'Impostor' },
    { id: 'g39', cat: 'Psikologi Gelap', q: 'Trauma yang diwariskan antar generasi (Epigenetic Trauma) sudah terbukti terjadi — trauma berat orang tua bisa [...] ke anak.', a: 'Mengubah Ekspresi Gen yang Diturunkan' },
    { id: 'g40', cat: 'Psikologi Gelap', q: 'Teknik "Foot-in-the-Door" adalah taktik manipulasi di mana orang pertama kali diminta [...] sebelum akhirnya diminta hal besar.', a: 'Hal Kecil' },
    { id: 'g41', cat: 'Psikologi Gelap', q: 'Fenomena "Sleeper Effect" menyatakan bahwa pesan dari sumber yang [...] bisa menjadi lebih persuasif seiring waktu, bukan berkurang.', a: 'Tidak Terpercaya' },
    { id: 'g42', cat: 'Psikologi Gelap', q: 'Kondisi "Erotomania" adalah delusi di mana seseorang yakin bahwa seseorang yang lebih terkenal [...] dengan mereka.', a: 'Sangat Jatuh Cinta' },
    { id: 'g43', cat: 'Psikologi Gelap', q: 'Saat otak manusia tidak mendapat informasi (seperti dalam tangki deprivasi sensori), setelah beberapa waktu otak mulai [...].', a: 'Menciptakan Hallusinasi untuk Mengisi Kekosongan' },
    { id: 'g44', cat: 'Psikologi Gelap', q: 'Para peneliti menemukan bahwa wajah-wajah yang "jahat" dalam film sering digambarkan dengan fitur [...] yang secara budaya dikaitkan dengan ketidakpercayaan.', a: 'Simetri Lebih Rendah, Rahang Menonjol, atau Mata Kecil' },
    { id: 'g45', cat: 'Psikologi Gelap', q: 'Dalam psikologi, "Splitting" adalah mekanisme pertahanan di mana seseorang melihat orang lain sebagai sepenuhnya [...] atau sepenuhnya jahat.', a: 'Baik' },
    { id: 'g46', cat: 'Psikologi Gelap', q: 'Kondisi "Alien Hand Syndrome" adalah kondisi di mana salah satu tangan seseorang bergerak [...] tanpa kendali pemiliknya.', a: 'Secara Mandiri' },
    { id: 'g47', cat: 'Psikologi Gelap', q: 'Eksperimen "Little Albert" yang kontroversial mengkondisikan seorang bayi untuk takut pada [...] melalui proses classical conditioning.', a: 'Tikus Putih' },
    { id: 'g48', cat: 'Psikologi Gelap', q: 'Fenomena "Dark Night of the Soul" adalah krisis psikologis-spiritual mendalam di mana seseorang merasa [...] total dari makna dan tujuan hidup.', a: 'Terputus' },
    { id: 'g49', cat: 'Psikologi Gelap', q: 'Penelitian menunjukkan bahwa keinginan untuk [...] — bahkan saat sendirian — adalah tanda kecerdasan dan kesehatan mental yang baik.', a: 'Berbicara dengan Diri Sendiri' },
    { id: 'g50', cat: 'Psikologi Gelap', q: 'Serangan sihir, "Nocebo Effect", adalah ketika seseorang yang diberitahu hal buruk akan terjadi kepadanya kemudian [...] karena keyakinannya semata.', a: 'Benar-benar Sakit atau Mati' },
    { id: 'g51', cat: 'Psikologi Gelap', q: 'Dalam kondisi "Sleep Paralysis", orang merasakan dirinya [...] dan sering melihat sosok gelap di kamarnya.', a: 'Tidak Bisa Bergerak Saat Setengah Sadar' },
  ],
};